// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reclosermodule/reclosermodule.proto

package reclosermodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specialized 61850 FSCC class.  LN: Schedule controller   Name: FSCC
type RecloserControlFSCC struct {
	// UML inherited base object
	LogicalNodeForControl *commonmodule.LogicalNodeForControl `protobuf:"bytes,1,opt,name=logicalNodeForControl,proto3" json:"logicalNodeForControl,omitempty"`
	// MISSING DOCUMENTATION!!!
	SwitchControlScheduleFSCH *commonmodule.SwitchControlScheduleFSCH `protobuf:"bytes,2,opt,name=switchControlScheduleFSCH,proto3" json:"switchControlScheduleFSCH,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                `json:"-"`
	XXX_unrecognized          []byte                                  `json:"-"`
	XXX_sizecache             int32                                   `json:"-"`
}

func (m *RecloserControlFSCC) Reset()         { *m = RecloserControlFSCC{} }
func (m *RecloserControlFSCC) String() string { return proto.CompactTextString(m) }
func (*RecloserControlFSCC) ProtoMessage()    {}
func (*RecloserControlFSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{0}
}

func (m *RecloserControlFSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserControlFSCC.Unmarshal(m, b)
}
func (m *RecloserControlFSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserControlFSCC.Marshal(b, m, deterministic)
}
func (m *RecloserControlFSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserControlFSCC.Merge(m, src)
}
func (m *RecloserControlFSCC) XXX_Size() int {
	return xxx_messageInfo_RecloserControlFSCC.Size(m)
}
func (m *RecloserControlFSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserControlFSCC.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserControlFSCC proto.InternalMessageInfo

func (m *RecloserControlFSCC) GetLogicalNodeForControl() *commonmodule.LogicalNodeForControl {
	if m != nil {
		return m.LogicalNodeForControl
	}
	return nil
}

func (m *RecloserControlFSCC) GetSwitchControlScheduleFSCH() *commonmodule.SwitchControlScheduleFSCH {
	if m != nil {
		return m.SwitchControlScheduleFSCH
	}
	return nil
}

// Recloser discrete control
type RecloserControl struct {
	// UML inherited base object
	ControlValue *commonmodule.ControlValue `protobuf:"bytes,1,opt,name=controlValue,proto3" json:"controlValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	Check *commonmodule.CheckConditions `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserControlFSCC  *RecloserControlFSCC `protobuf:"bytes,3,opt,name=recloserControlFSCC,proto3" json:"recloserControlFSCC,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecloserControl) Reset()         { *m = RecloserControl{} }
func (m *RecloserControl) String() string { return proto.CompactTextString(m) }
func (*RecloserControl) ProtoMessage()    {}
func (*RecloserControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{1}
}

func (m *RecloserControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserControl.Unmarshal(m, b)
}
func (m *RecloserControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserControl.Marshal(b, m, deterministic)
}
func (m *RecloserControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserControl.Merge(m, src)
}
func (m *RecloserControl) XXX_Size() int {
	return xxx_messageInfo_RecloserControl.Size(m)
}
func (m *RecloserControl) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserControl.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserControl proto.InternalMessageInfo

func (m *RecloserControl) GetControlValue() *commonmodule.ControlValue {
	if m != nil {
		return m.ControlValue
	}
	return nil
}

func (m *RecloserControl) GetCheck() *commonmodule.CheckConditions {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *RecloserControl) GetRecloserControlFSCC() *RecloserControlFSCC {
	if m != nil {
		return m.RecloserControlFSCC
	}
	return nil
}

// Pole-mounted fault interrupter with built-in phase and ground relays, current transformer (CT),
// and supplemental controls.
type Recloser struct {
	// UML inherited base object
	ConductingEquipment *commonmodule.ConductingEquipment `protobuf:"bytes,1,opt,name=conductingEquipment,proto3" json:"conductingEquipment,omitempty"`
	// MISSING DOCUMENTATION!!!
	NormalOpen           *wrappers.BoolValue `protobuf:"bytes,2,opt,name=normalOpen,proto3" json:"normalOpen,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Recloser) Reset()         { *m = Recloser{} }
func (m *Recloser) String() string { return proto.CompactTextString(m) }
func (*Recloser) ProtoMessage()    {}
func (*Recloser) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{2}
}

func (m *Recloser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recloser.Unmarshal(m, b)
}
func (m *Recloser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recloser.Marshal(b, m, deterministic)
}
func (m *Recloser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recloser.Merge(m, src)
}
func (m *Recloser) XXX_Size() int {
	return xxx_messageInfo_Recloser.Size(m)
}
func (m *Recloser) XXX_DiscardUnknown() {
	xxx_messageInfo_Recloser.DiscardUnknown(m)
}

var xxx_messageInfo_Recloser proto.InternalMessageInfo

func (m *Recloser) GetConductingEquipment() *commonmodule.ConductingEquipment {
	if m != nil {
		return m.ConductingEquipment
	}
	return nil
}

func (m *Recloser) GetNormalOpen() *wrappers.BoolValue {
	if m != nil {
		return m.NormalOpen
	}
	return nil
}

// Recloser control profile.  Instructs an end device (or an end device group) to perform a
// specified action.
type RecloserControlProfile struct {
	// UML inherited base object
	ControlMessageInfo *commonmodule.ControlMessageInfo `protobuf:"bytes,1,opt,name=controlMessageInfo,proto3" json:"controlMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Recloser *Recloser `protobuf:"bytes,3,opt,name=recloser,proto3" json:"recloser,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserControl      *RecloserControl `protobuf:"bytes,4,opt,name=recloserControl,proto3" json:"recloserControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RecloserControlProfile) Reset()         { *m = RecloserControlProfile{} }
func (m *RecloserControlProfile) String() string { return proto.CompactTextString(m) }
func (*RecloserControlProfile) ProtoMessage()    {}
func (*RecloserControlProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{3}
}

func (m *RecloserControlProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserControlProfile.Unmarshal(m, b)
}
func (m *RecloserControlProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserControlProfile.Marshal(b, m, deterministic)
}
func (m *RecloserControlProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserControlProfile.Merge(m, src)
}
func (m *RecloserControlProfile) XXX_Size() int {
	return xxx_messageInfo_RecloserControlProfile.Size(m)
}
func (m *RecloserControlProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserControlProfile.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserControlProfile proto.InternalMessageInfo

func (m *RecloserControlProfile) GetControlMessageInfo() *commonmodule.ControlMessageInfo {
	if m != nil {
		return m.ControlMessageInfo
	}
	return nil
}

func (m *RecloserControlProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *RecloserControlProfile) GetRecloser() *Recloser {
	if m != nil {
		return m.Recloser
	}
	return nil
}

func (m *RecloserControlProfile) GetRecloserControl() *RecloserControl {
	if m != nil {
		return m.RecloserControl
	}
	return nil
}

// OpenFMB specialization for RecloserDiscreteControlProfile: Added blk  LN: Circuit
// breaker   Name: XCBR
type RecloserDiscreteControlXCBR struct {
	// UML inherited base object
	LogicalNodeForControl *commonmodule.LogicalNodeForControl `protobuf:"bytes,1,opt,name=logicalNodeForControl,proto3" json:"logicalNodeForControl,omitempty"`
	// MISSING DOCUMENTATION!!!
	Pos                  *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecloserDiscreteControlXCBR) Reset()         { *m = RecloserDiscreteControlXCBR{} }
func (m *RecloserDiscreteControlXCBR) String() string { return proto.CompactTextString(m) }
func (*RecloserDiscreteControlXCBR) ProtoMessage()    {}
func (*RecloserDiscreteControlXCBR) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{4}
}

func (m *RecloserDiscreteControlXCBR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserDiscreteControlXCBR.Unmarshal(m, b)
}
func (m *RecloserDiscreteControlXCBR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserDiscreteControlXCBR.Marshal(b, m, deterministic)
}
func (m *RecloserDiscreteControlXCBR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserDiscreteControlXCBR.Merge(m, src)
}
func (m *RecloserDiscreteControlXCBR) XXX_Size() int {
	return xxx_messageInfo_RecloserDiscreteControlXCBR.Size(m)
}
func (m *RecloserDiscreteControlXCBR) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserDiscreteControlXCBR.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserDiscreteControlXCBR proto.InternalMessageInfo

func (m *RecloserDiscreteControlXCBR) GetLogicalNodeForControl() *commonmodule.LogicalNodeForControl {
	if m != nil {
		return m.LogicalNodeForControl
	}
	return nil
}

func (m *RecloserDiscreteControlXCBR) GetPos() *commonmodule.ControlDPC {
	if m != nil {
		return m.Pos
	}
	return nil
}

// Recloser discrete control
type RecloserDiscreteControl struct {
	// UML inherited base object
	ControlValue *commonmodule.ControlValue `protobuf:"bytes,1,opt,name=controlValue,proto3" json:"controlValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	Check *commonmodule.CheckConditions `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserDiscreteControlXCBR *RecloserDiscreteControlXCBR `protobuf:"bytes,3,opt,name=recloserDiscreteControlXCBR,proto3" json:"recloserDiscreteControlXCBR,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                     `json:"-"`
	XXX_unrecognized            []byte                       `json:"-"`
	XXX_sizecache               int32                        `json:"-"`
}

func (m *RecloserDiscreteControl) Reset()         { *m = RecloserDiscreteControl{} }
func (m *RecloserDiscreteControl) String() string { return proto.CompactTextString(m) }
func (*RecloserDiscreteControl) ProtoMessage()    {}
func (*RecloserDiscreteControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{5}
}

func (m *RecloserDiscreteControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserDiscreteControl.Unmarshal(m, b)
}
func (m *RecloserDiscreteControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserDiscreteControl.Marshal(b, m, deterministic)
}
func (m *RecloserDiscreteControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserDiscreteControl.Merge(m, src)
}
func (m *RecloserDiscreteControl) XXX_Size() int {
	return xxx_messageInfo_RecloserDiscreteControl.Size(m)
}
func (m *RecloserDiscreteControl) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserDiscreteControl.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserDiscreteControl proto.InternalMessageInfo

func (m *RecloserDiscreteControl) GetControlValue() *commonmodule.ControlValue {
	if m != nil {
		return m.ControlValue
	}
	return nil
}

func (m *RecloserDiscreteControl) GetCheck() *commonmodule.CheckConditions {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *RecloserDiscreteControl) GetRecloserDiscreteControlXCBR() *RecloserDiscreteControlXCBR {
	if m != nil {
		return m.RecloserDiscreteControlXCBR
	}
	return nil
}

// Recloser control profile.  Instructs an end device (or an end device group) to perform a
// specified action.
type RecloserDiscreteControlProfile struct {
	// UML inherited base object
	ControlMessageInfo *commonmodule.ControlMessageInfo `protobuf:"bytes,1,opt,name=controlMessageInfo,proto3" json:"controlMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Recloser *Recloser `protobuf:"bytes,3,opt,name=recloser,proto3" json:"recloser,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserDiscreteControl *RecloserDiscreteControl `protobuf:"bytes,4,opt,name=recloserDiscreteControl,proto3" json:"recloserDiscreteControl,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *RecloserDiscreteControlProfile) Reset()         { *m = RecloserDiscreteControlProfile{} }
func (m *RecloserDiscreteControlProfile) String() string { return proto.CompactTextString(m) }
func (*RecloserDiscreteControlProfile) ProtoMessage()    {}
func (*RecloserDiscreteControlProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{6}
}

func (m *RecloserDiscreteControlProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserDiscreteControlProfile.Unmarshal(m, b)
}
func (m *RecloserDiscreteControlProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserDiscreteControlProfile.Marshal(b, m, deterministic)
}
func (m *RecloserDiscreteControlProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserDiscreteControlProfile.Merge(m, src)
}
func (m *RecloserDiscreteControlProfile) XXX_Size() int {
	return xxx_messageInfo_RecloserDiscreteControlProfile.Size(m)
}
func (m *RecloserDiscreteControlProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserDiscreteControlProfile.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserDiscreteControlProfile proto.InternalMessageInfo

func (m *RecloserDiscreteControlProfile) GetControlMessageInfo() *commonmodule.ControlMessageInfo {
	if m != nil {
		return m.ControlMessageInfo
	}
	return nil
}

func (m *RecloserDiscreteControlProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *RecloserDiscreteControlProfile) GetRecloser() *Recloser {
	if m != nil {
		return m.Recloser
	}
	return nil
}

func (m *RecloserDiscreteControlProfile) GetRecloserDiscreteControl() *RecloserDiscreteControl {
	if m != nil {
		return m.RecloserDiscreteControl
	}
	return nil
}

// Recloser event
type RecloserEvent struct {
	// UML inherited base object
	EventValue *commonmodule.EventValue `protobuf:"bytes,1,opt,name=eventValue,proto3" json:"eventValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	StatusAndEventXCBR   *commonmodule.StatusAndEventXCBR `protobuf:"bytes,2,opt,name=statusAndEventXCBR,proto3" json:"statusAndEventXCBR,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *RecloserEvent) Reset()         { *m = RecloserEvent{} }
func (m *RecloserEvent) String() string { return proto.CompactTextString(m) }
func (*RecloserEvent) ProtoMessage()    {}
func (*RecloserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{7}
}

func (m *RecloserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserEvent.Unmarshal(m, b)
}
func (m *RecloserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserEvent.Marshal(b, m, deterministic)
}
func (m *RecloserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserEvent.Merge(m, src)
}
func (m *RecloserEvent) XXX_Size() int {
	return xxx_messageInfo_RecloserEvent.Size(m)
}
func (m *RecloserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserEvent proto.InternalMessageInfo

func (m *RecloserEvent) GetEventValue() *commonmodule.EventValue {
	if m != nil {
		return m.EventValue
	}
	return nil
}

func (m *RecloserEvent) GetStatusAndEventXCBR() *commonmodule.StatusAndEventXCBR {
	if m != nil {
		return m.StatusAndEventXCBR
	}
	return nil
}

// Recloser event profile
type RecloserEventProfile struct {
	// UML inherited base object
	EventMessageInfo *commonmodule.EventMessageInfo `protobuf:"bytes,1,opt,name=eventMessageInfo,proto3" json:"eventMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Recloser *Recloser `protobuf:"bytes,3,opt,name=recloser,proto3" json:"recloser,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserEvent        *RecloserEvent `protobuf:"bytes,4,opt,name=recloserEvent,proto3" json:"recloserEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecloserEventProfile) Reset()         { *m = RecloserEventProfile{} }
func (m *RecloserEventProfile) String() string { return proto.CompactTextString(m) }
func (*RecloserEventProfile) ProtoMessage()    {}
func (*RecloserEventProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{8}
}

func (m *RecloserEventProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserEventProfile.Unmarshal(m, b)
}
func (m *RecloserEventProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserEventProfile.Marshal(b, m, deterministic)
}
func (m *RecloserEventProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserEventProfile.Merge(m, src)
}
func (m *RecloserEventProfile) XXX_Size() int {
	return xxx_messageInfo_RecloserEventProfile.Size(m)
}
func (m *RecloserEventProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserEventProfile.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserEventProfile proto.InternalMessageInfo

func (m *RecloserEventProfile) GetEventMessageInfo() *commonmodule.EventMessageInfo {
	if m != nil {
		return m.EventMessageInfo
	}
	return nil
}

func (m *RecloserEventProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *RecloserEventProfile) GetRecloser() *Recloser {
	if m != nil {
		return m.Recloser
	}
	return nil
}

func (m *RecloserEventProfile) GetRecloserEvent() *RecloserEvent {
	if m != nil {
		return m.RecloserEvent
	}
	return nil
}

// Recloser reading value
type RecloserReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	DiffReadingMMXU *commonmodule.ReadingMMXU `protobuf:"bytes,2,opt,name=diffReadingMMXU,proto3" json:"diffReadingMMXU,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,3,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,4,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,5,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RecloserReading) Reset()         { *m = RecloserReading{} }
func (m *RecloserReading) String() string { return proto.CompactTextString(m) }
func (*RecloserReading) ProtoMessage()    {}
func (*RecloserReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{9}
}

func (m *RecloserReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserReading.Unmarshal(m, b)
}
func (m *RecloserReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserReading.Marshal(b, m, deterministic)
}
func (m *RecloserReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserReading.Merge(m, src)
}
func (m *RecloserReading) XXX_Size() int {
	return xxx_messageInfo_RecloserReading.Size(m)
}
func (m *RecloserReading) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserReading.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserReading proto.InternalMessageInfo

func (m *RecloserReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *RecloserReading) GetDiffReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.DiffReadingMMXU
	}
	return nil
}

func (m *RecloserReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *RecloserReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *RecloserReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Recloser reading profile
type RecloserReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Recloser *Recloser `protobuf:"bytes,3,opt,name=recloser,proto3" json:"recloser,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserReading      []*RecloserReading `protobuf:"bytes,4,rep,name=recloserReading,proto3" json:"recloserReading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecloserReadingProfile) Reset()         { *m = RecloserReadingProfile{} }
func (m *RecloserReadingProfile) String() string { return proto.CompactTextString(m) }
func (*RecloserReadingProfile) ProtoMessage()    {}
func (*RecloserReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{10}
}

func (m *RecloserReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserReadingProfile.Unmarshal(m, b)
}
func (m *RecloserReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserReadingProfile.Marshal(b, m, deterministic)
}
func (m *RecloserReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserReadingProfile.Merge(m, src)
}
func (m *RecloserReadingProfile) XXX_Size() int {
	return xxx_messageInfo_RecloserReadingProfile.Size(m)
}
func (m *RecloserReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserReadingProfile proto.InternalMessageInfo

func (m *RecloserReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *RecloserReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *RecloserReadingProfile) GetRecloser() *Recloser {
	if m != nil {
		return m.Recloser
	}
	return nil
}

func (m *RecloserReadingProfile) GetRecloserReading() []*RecloserReading {
	if m != nil {
		return m.RecloserReading
	}
	return nil
}

// Recloser status
type RecloserStatus struct {
	// UML inherited base object
	StatusValue *commonmodule.StatusValue `protobuf:"bytes,1,opt,name=statusValue,proto3" json:"statusValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	StatusAndEventXCBR   *commonmodule.StatusAndEventXCBR `protobuf:"bytes,2,opt,name=statusAndEventXCBR,proto3" json:"statusAndEventXCBR,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *RecloserStatus) Reset()         { *m = RecloserStatus{} }
func (m *RecloserStatus) String() string { return proto.CompactTextString(m) }
func (*RecloserStatus) ProtoMessage()    {}
func (*RecloserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{11}
}

func (m *RecloserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserStatus.Unmarshal(m, b)
}
func (m *RecloserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserStatus.Marshal(b, m, deterministic)
}
func (m *RecloserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserStatus.Merge(m, src)
}
func (m *RecloserStatus) XXX_Size() int {
	return xxx_messageInfo_RecloserStatus.Size(m)
}
func (m *RecloserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserStatus proto.InternalMessageInfo

func (m *RecloserStatus) GetStatusValue() *commonmodule.StatusValue {
	if m != nil {
		return m.StatusValue
	}
	return nil
}

func (m *RecloserStatus) GetStatusAndEventXCBR() *commonmodule.StatusAndEventXCBR {
	if m != nil {
		return m.StatusAndEventXCBR
	}
	return nil
}

// Recloser status profile
type RecloserStatusProfile struct {
	// UML inherited base object
	StatusMessageInfo *commonmodule.StatusMessageInfo `protobuf:"bytes,1,opt,name=statusMessageInfo,proto3" json:"statusMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Recloser *Recloser `protobuf:"bytes,3,opt,name=recloser,proto3" json:"recloser,omitempty"`
	// MISSING DOCUMENTATION!!!
	RecloserStatus       *RecloserStatus `protobuf:"bytes,4,opt,name=recloserStatus,proto3" json:"recloserStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecloserStatusProfile) Reset()         { *m = RecloserStatusProfile{} }
func (m *RecloserStatusProfile) String() string { return proto.CompactTextString(m) }
func (*RecloserStatusProfile) ProtoMessage()    {}
func (*RecloserStatusProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9430b02f4d470548, []int{12}
}

func (m *RecloserStatusProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecloserStatusProfile.Unmarshal(m, b)
}
func (m *RecloserStatusProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecloserStatusProfile.Marshal(b, m, deterministic)
}
func (m *RecloserStatusProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecloserStatusProfile.Merge(m, src)
}
func (m *RecloserStatusProfile) XXX_Size() int {
	return xxx_messageInfo_RecloserStatusProfile.Size(m)
}
func (m *RecloserStatusProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_RecloserStatusProfile.DiscardUnknown(m)
}

var xxx_messageInfo_RecloserStatusProfile proto.InternalMessageInfo

func (m *RecloserStatusProfile) GetStatusMessageInfo() *commonmodule.StatusMessageInfo {
	if m != nil {
		return m.StatusMessageInfo
	}
	return nil
}

func (m *RecloserStatusProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *RecloserStatusProfile) GetRecloser() *Recloser {
	if m != nil {
		return m.Recloser
	}
	return nil
}

func (m *RecloserStatusProfile) GetRecloserStatus() *RecloserStatus {
	if m != nil {
		return m.RecloserStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*RecloserControlFSCC)(nil), "reclosermodule.RecloserControlFSCC")
	proto.RegisterType((*RecloserControl)(nil), "reclosermodule.RecloserControl")
	proto.RegisterType((*Recloser)(nil), "reclosermodule.Recloser")
	proto.RegisterType((*RecloserControlProfile)(nil), "reclosermodule.RecloserControlProfile")
	proto.RegisterType((*RecloserDiscreteControlXCBR)(nil), "reclosermodule.RecloserDiscreteControlXCBR")
	proto.RegisterType((*RecloserDiscreteControl)(nil), "reclosermodule.RecloserDiscreteControl")
	proto.RegisterType((*RecloserDiscreteControlProfile)(nil), "reclosermodule.RecloserDiscreteControlProfile")
	proto.RegisterType((*RecloserEvent)(nil), "reclosermodule.RecloserEvent")
	proto.RegisterType((*RecloserEventProfile)(nil), "reclosermodule.RecloserEventProfile")
	proto.RegisterType((*RecloserReading)(nil), "reclosermodule.RecloserReading")
	proto.RegisterType((*RecloserReadingProfile)(nil), "reclosermodule.RecloserReadingProfile")
	proto.RegisterType((*RecloserStatus)(nil), "reclosermodule.RecloserStatus")
	proto.RegisterType((*RecloserStatusProfile)(nil), "reclosermodule.RecloserStatusProfile")
}

func init() {
	proto.RegisterFile("reclosermodule/reclosermodule.proto", fileDescriptor_9430b02f4d470548)
}

var fileDescriptor_9430b02f4d470548 = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcf, 0x8f, 0xdb, 0x44,
	0x14, 0x96, 0x9d, 0x2d, 0xda, 0xbe, 0x6d, 0xbb, 0x74, 0x96, 0x76, 0xbd, 0x5b, 0x75, 0x77, 0x71,
	0x0f, 0x45, 0xa0, 0x24, 0x88, 0x8a, 0x4b, 0x91, 0x2a, 0x35, 0x4e, 0x56, 0x54, 0x22, 0x25, 0x9a,
	0xa4, 0x65, 0xe9, 0xa5, 0x72, 0xec, 0x89, 0x63, 0xd5, 0xf6, 0x18, 0xdb, 0x61, 0xaf, 0x9c, 0x80,
	0x0b, 0x52, 0x8f, 0x5c, 0xb9, 0x16, 0x24, 0x0e, 0x68, 0x2f, 0x1c, 0x10, 0x7f, 0x07, 0x12, 0x7f,
	0x02, 0x27, 0xfe, 0x01, 0x64, 0xfb, 0x4d, 0x32, 0xfe, 0xd5, 0xf4, 0xd2, 0x45, 0xea, 0xcd, 0xf6,
	0x7c, 0xdf, 0x37, 0xef, 0xbd, 0xef, 0xcd, 0x1b, 0x19, 0x6e, 0x45, 0xcc, 0xf2, 0x78, 0xcc, 0x22,
	0x9f, 0xdb, 0x0b, 0x8f, 0x75, 0x8b, 0xaf, 0x9d, 0x30, 0xe2, 0x09, 0x27, 0x57, 0x8a, 0x5f, 0xf7,
	0x2f, 0x2e, 0x7c, 0x2f, 0x5f, 0xda, 0x3f, 0x70, 0x38, 0x77, 0x3c, 0xd6, 0xcd, 0xde, 0xa6, 0x8b,
	0x59, 0xf7, 0x34, 0x32, 0xc3, 0x90, 0x45, 0x31, 0xae, 0x1f, 0x5a, 0xdc, 0xf7, 0x79, 0x80, 0xea,
	0xf2, 0x4b, 0x0e, 0xd0, 0xff, 0x56, 0x60, 0x87, 0xa2, 0xbc, 0xc1, 0x83, 0x24, 0xe2, 0xde, 0xf1,
	0xd8, 0x30, 0xc8, 0x53, 0xb8, 0xe6, 0x71, 0xc7, 0xb5, 0x4c, 0xef, 0x21, 0xb7, 0xd9, 0x31, 0x17,
	0x8b, 0x9a, 0x72, 0xa4, 0xbc, 0xb7, 0xf5, 0xd1, 0xad, 0x4e, 0x41, 0xeb, 0xb3, 0x3a, 0x68, 0x6f,
	0xe3, 0x9b, 0x33, 0x4d, 0xa1, 0xf5, 0x3a, 0x84, 0xc1, 0x5e, 0x7c, 0xea, 0x26, 0xd6, 0x1c, 0x3f,
	0x8c, 0xad, 0x39, 0x4b, 0xb5, 0x8e, 0xc7, 0xc6, 0xa7, 0x9a, 0x9a, 0x6d, 0x72, 0xbb, 0xb8, 0xc9,
	0xb8, 0x09, 0x4e, 0x9b, 0x95, 0xf4, 0x7f, 0x14, 0xd8, 0x2e, 0xe5, 0x47, 0xfa, 0x70, 0xc9, 0xca,
	0x1f, 0x1f, 0x9b, 0xde, 0x82, 0x61, 0x4a, 0xfb, 0xc5, 0xdd, 0x0c, 0x09, 0x81, 0x99, 0x14, 0x58,
	0xe4, 0x0e, 0x5c, 0xb0, 0xe6, 0xcc, 0x7a, 0x86, 0xc1, 0xde, 0x2c, 0xd1, 0xd3, 0x25, 0x83, 0x07,
	0xb6, 0x9b, 0xb8, 0x3c, 0x88, 0x69, 0x8e, 0x25, 0x4f, 0x61, 0x27, 0xaa, 0x56, 0x5b, 0x6b, 0x61,
	0x51, 0x4b, 0xf6, 0xd7, 0x18, 0xd3, 0xdb, 0xfc, 0xfe, 0x4c, 0x53, 0x9e, 0xa7, 0xe1, 0xd4, 0x29,
	0xe9, 0x3f, 0x29, 0xb0, 0x29, 0x68, 0xe4, 0x4b, 0xd8, 0xb1, 0x78, 0x60, 0x2f, 0xac, 0xc4, 0x0d,
	0x9c, 0xc1, 0x57, 0x0b, 0x37, 0xf4, 0x59, 0x90, 0x60, 0xbe, 0xef, 0x56, 0xf2, 0x2d, 0x03, 0x31,
	0xed, 0x3a, 0x0d, 0x72, 0x17, 0x20, 0xe0, 0x91, 0x6f, 0x7a, 0x9f, 0x87, 0x2c, 0xc0, 0x12, 0xec,
	0x77, 0xf2, 0x6e, 0xec, 0x88, 0x6e, 0xec, 0xf4, 0x38, 0x56, 0x8b, 0x4a, 0x68, 0xfd, 0x77, 0x15,
	0xae, 0x97, 0x52, 0x1b, 0x45, 0x7c, 0xe6, 0x7a, 0x8c, 0x3c, 0x06, 0x82, 0x45, 0x1e, 0xb2, 0x38,
	0x36, 0x1d, 0xf6, 0x20, 0x98, 0x71, 0x0c, 0xf8, 0xa8, 0xd6, 0x20, 0x09, 0x87, 0xf1, 0xd6, 0x28,
	0x90, 0x36, 0xb4, 0x5c, 0x66, 0x63, 0x9c, 0x57, 0x8b, 0x42, 0x0f, 0x06, 0x7d, 0xa9, 0xaa, 0x29,
	0x8e, 0xdc, 0x83, 0x4d, 0x51, 0x5c, 0xf4, 0x46, 0x6b, 0xf2, 0x46, 0xa2, 0x2e, 0x39, 0x64, 0x0c,
	0xdb, 0x25, 0x73, 0xb4, 0x8d, 0x4c, 0xe6, 0x70, 0x8d, 0xc5, 0x92, 0x5a, 0x59, 0xe1, 0xee, 0xc6,
	0x9f, 0xff, 0x6a, 0x8a, 0xfe, 0x42, 0x81, 0x1b, 0x82, 0xd4, 0x77, 0x63, 0x2b, 0x62, 0x09, 0x43,
	0xc4, 0x89, 0xd1, 0xa3, 0xaf, 0xff, 0xe0, 0xbe, 0x0f, 0xad, 0x11, 0x8f, 0xb1, 0x94, 0x5a, 0xad,
	0x27, 0xfd, 0x91, 0x41, 0x53, 0x90, 0xfe, 0x83, 0x0a, 0xbb, 0x0d, 0xc1, 0xfe, 0x9f, 0xa7, 0xf0,
	0x14, 0x6e, 0x44, 0xcd, 0x25, 0x44, 0xc7, 0x3f, 0x68, 0xb2, 0xaa, 0x86, 0x22, 0xd9, 0xf6, 0x32,
	0x65, 0xfd, 0x2f, 0x15, 0x0e, 0x1a, 0x64, 0xde, 0xb0, 0x13, 0xf0, 0x0c, 0x76, 0x1b, 0x0a, 0x81,
	0x27, 0xe1, 0xf6, 0x2b, 0x96, 0x57, 0x52, 0x6f, 0x52, 0xc4, 0x93, 0xf1, 0xb3, 0x02, 0x97, 0x85,
	0xc8, 0xe0, 0xeb, 0x74, 0x48, 0xdd, 0x03, 0x60, 0xe9, 0x83, 0xdc, 0x60, 0xa5, 0x8e, 0x1d, 0x2c,
	0xd7, 0xb1, 0x76, 0x12, 0x83, 0x3c, 0x01, 0x12, 0x27, 0x66, 0xb2, 0x88, 0xef, 0x07, 0x76, 0x06,
	0xcc, 0xda, 0x43, 0xad, 0xf3, 0x62, 0x5c, 0xc1, 0x49, 0x81, 0xd7, 0xa8, 0xe8, 0xbf, 0xa8, 0xf0,
	0x4e, 0x21, 0x5a, 0xd1, 0x00, 0x23, 0x78, 0x3b, 0x0b, 0xa1, 0x6a, 0xff, 0x41, 0x4d, 0xe8, 0x55,
	0xf3, 0x2b, 0xec, 0xf3, 0xb6, 0x7e, 0x08, 0x97, 0x23, 0x39, 0x31, 0x34, 0xfc, 0x66, 0x93, 0x48,
	0x06, 0x92, 0x94, 0x8a, 0x6c, 0x34, 0xf7, 0x79, 0x6b, 0x75, 0x8f, 0x53, 0x66, 0xda, 0x6e, 0xe0,
	0x90, 0x6f, 0x15, 0xd0, 0x6b, 0xee, 0xa6, 0x09, 0x8b, 0x7c, 0x37, 0x30, 0x3d, 0x84, 0x61, 0xf1,
	0x3e, 0x5c, 0x7b, 0xdd, 0x95, 0x78, 0x58, 0xce, 0x57, 0xd8, 0x81, 0x18, 0xb0, 0x6d, 0xbb, 0xb3,
	0x19, 0xbe, 0x0e, 0x87, 0x27, 0x8f, 0xb0, 0xd8, 0x7b, 0xc5, 0x4d, 0x25, 0x00, 0x2d, 0x33, 0xc8,
	0xc7, 0x70, 0x31, 0x9c, 0x9b, 0x31, 0x1b, 0x0e, 0x27, 0x0f, 0xb1, 0xee, 0xbb, 0x45, 0xfa, 0x48,
	0x2c, 0xd3, 0x15, 0x92, 0x7c, 0x02, 0x5b, 0x91, 0x50, 0x99, 0x50, 0xac, 0x75, 0xd3, 0xbe, 0x13,
	0x4a, 0x65, 0x74, 0x81, 0x7c, 0xf2, 0x48, 0xbb, 0xb0, 0x2e, 0x68, 0x19, 0xad, 0xff, 0x21, 0x5d,
	0xe3, 0x08, 0x92, 0x86, 0x98, 0x40, 0xae, 0x1b, 0x62, 0xb4, 0x82, 0x13, 0x43, 0xac, 0xaa, 0x70,
	0xde, 0x9d, 0xfc, 0xc5, 0xea, 0x1a, 0x17, 0xcd, 0xb4, 0x71, 0xd4, 0x7a, 0xd9, 0x35, 0x2e, 0x7a,
	0xe7, 0x92, 0x50, 0xfb, 0xf1, 0x4c, 0x53, 0x69, 0x59, 0x05, 0x7b, 0xfa, 0x57, 0x05, 0xae, 0x08,
	0x62, 0x3e, 0x3f, 0xc8, 0x7d, 0xd8, 0xca, 0x67, 0x85, 0x3c, 0xb2, 0xf6, 0xea, 0x46, 0x8d, 0x3c,
	0xb3, 0x64, 0xce, 0x6b, 0x1d, 0x5a, 0xbf, 0xa9, 0x70, 0xad, 0x18, 0xb1, 0x70, 0x7c, 0x0c, 0x57,
	0x73, 0x7c, 0xd5, 0xf0, 0xc3, 0xba, 0x4d, 0xab, 0x7e, 0x57, 0xf9, 0xe7, 0x6d, 0xf7, 0x08, 0x96,
	0x7f, 0x5a, 0x79, 0x90, 0x78, 0x9a, 0x0e, 0x9a, 0x54, 0x72, 0x94, 0xa4, 0x55, 0xe2, 0xe7, 0x3e,
	0xf7, 0xbe, 0x53, 0xe0, 0x3a, 0x0f, 0x59, 0x30, 0xf3, 0xa7, 0x25, 0xa5, 0x91, 0xf2, 0x84, 0x3a,
	0x6e, 0xe2, 0x99, 0xd3, 0x34, 0xb9, 0x2e, 0x82, 0xba, 0x61, 0x9c, 0x3e, 0xc7, 0xab, 0xbf, 0x3a,
	0x87, 0xb7, 0x71, 0xad, 0xcd, 0xc3, 0xb8, 0xbd, 0xfc, 0x2e, 0x08, 0x45, 0xd5, 0x17, 0x6a, 0xc3,
	0x76, 0xd3, 0xb7, 0x32, 0xe6, 0x9d, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xa3, 0xf4, 0x80,
	0x77, 0x0e, 0x00, 0x00,
}
