// Code generated by protoc-gen-go. DO NOT EDIT.
// source: breakermodule/breakermodule.proto

package breakermodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OpenFMB specialization for BreakerDiscreteControlProfile: Added blk  LN: Circuit breaker   Name:
// XCBR
type BreakerDiscreteControlXCBR struct {
	// UML inherited base object
	LogicalNodeForControl *commonmodule.LogicalNodeForControl `protobuf:"bytes,1,opt,name=logicalNodeForControl,proto3" json:"logicalNodeForControl,omitempty"`
	// MISSING DOCUMENTATION!!!
	Pos                  *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BreakerDiscreteControlXCBR) Reset()         { *m = BreakerDiscreteControlXCBR{} }
func (m *BreakerDiscreteControlXCBR) String() string { return proto.CompactTextString(m) }
func (*BreakerDiscreteControlXCBR) ProtoMessage()    {}
func (*BreakerDiscreteControlXCBR) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{0}
}

func (m *BreakerDiscreteControlXCBR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerDiscreteControlXCBR.Unmarshal(m, b)
}
func (m *BreakerDiscreteControlXCBR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerDiscreteControlXCBR.Marshal(b, m, deterministic)
}
func (m *BreakerDiscreteControlXCBR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerDiscreteControlXCBR.Merge(m, src)
}
func (m *BreakerDiscreteControlXCBR) XXX_Size() int {
	return xxx_messageInfo_BreakerDiscreteControlXCBR.Size(m)
}
func (m *BreakerDiscreteControlXCBR) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerDiscreteControlXCBR.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerDiscreteControlXCBR proto.InternalMessageInfo

func (m *BreakerDiscreteControlXCBR) GetLogicalNodeForControl() *commonmodule.LogicalNodeForControl {
	if m != nil {
		return m.LogicalNodeForControl
	}
	return nil
}

func (m *BreakerDiscreteControlXCBR) GetPos() *commonmodule.ControlDPC {
	if m != nil {
		return m.Pos
	}
	return nil
}

// Breaker discrete control class
type BreakerDiscreteControl struct {
	// UML inherited base object
	ControlValue *commonmodule.ControlValue `protobuf:"bytes,1,opt,name=controlValue,proto3" json:"controlValue,omitempty"`
	// IEC61850 enhanced control parameters.
	Check *commonmodule.CheckConditions `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	// MISSING DOCUMENTATION!!!
	BreakerDiscreteControlXCBR *BreakerDiscreteControlXCBR `protobuf:"bytes,3,opt,name=breakerDiscreteControlXCBR,proto3" json:"breakerDiscreteControlXCBR,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                    `json:"-"`
	XXX_unrecognized           []byte                      `json:"-"`
	XXX_sizecache              int32                       `json:"-"`
}

func (m *BreakerDiscreteControl) Reset()         { *m = BreakerDiscreteControl{} }
func (m *BreakerDiscreteControl) String() string { return proto.CompactTextString(m) }
func (*BreakerDiscreteControl) ProtoMessage()    {}
func (*BreakerDiscreteControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{1}
}

func (m *BreakerDiscreteControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerDiscreteControl.Unmarshal(m, b)
}
func (m *BreakerDiscreteControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerDiscreteControl.Marshal(b, m, deterministic)
}
func (m *BreakerDiscreteControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerDiscreteControl.Merge(m, src)
}
func (m *BreakerDiscreteControl) XXX_Size() int {
	return xxx_messageInfo_BreakerDiscreteControl.Size(m)
}
func (m *BreakerDiscreteControl) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerDiscreteControl.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerDiscreteControl proto.InternalMessageInfo

func (m *BreakerDiscreteControl) GetControlValue() *commonmodule.ControlValue {
	if m != nil {
		return m.ControlValue
	}
	return nil
}

func (m *BreakerDiscreteControl) GetCheck() *commonmodule.CheckConditions {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *BreakerDiscreteControl) GetBreakerDiscreteControlXCBR() *BreakerDiscreteControlXCBR {
	if m != nil {
		return m.BreakerDiscreteControlXCBR
	}
	return nil
}

// A mechanical switching device capable of making, carrying, and breaking currents under normal
// circuit conditions and also making, carrying for a specified time, and breaking currents under
// specified abnormal circuit conditions e.g.  those of short circuit.
type Breaker struct {
	// UML inherited base object
	ConductingEquipment  *commonmodule.ConductingEquipment `protobuf:"bytes,1,opt,name=conductingEquipment,proto3" json:"conductingEquipment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Breaker) Reset()         { *m = Breaker{} }
func (m *Breaker) String() string { return proto.CompactTextString(m) }
func (*Breaker) ProtoMessage()    {}
func (*Breaker) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{2}
}

func (m *Breaker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Breaker.Unmarshal(m, b)
}
func (m *Breaker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Breaker.Marshal(b, m, deterministic)
}
func (m *Breaker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Breaker.Merge(m, src)
}
func (m *Breaker) XXX_Size() int {
	return xxx_messageInfo_Breaker.Size(m)
}
func (m *Breaker) XXX_DiscardUnknown() {
	xxx_messageInfo_Breaker.DiscardUnknown(m)
}

var xxx_messageInfo_Breaker proto.InternalMessageInfo

func (m *Breaker) GetConductingEquipment() *commonmodule.ConductingEquipment {
	if m != nil {
		return m.ConductingEquipment
	}
	return nil
}

// Instructs an end device (or an end device group) to perform a specified action.
type BreakerDiscreteControlProfile struct {
	// UML inherited base object
	ControlMessageInfo *commonmodule.ControlMessageInfo `protobuf:"bytes,1,opt,name=controlMessageInfo,proto3" json:"controlMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Breaker *Breaker `protobuf:"bytes,2,opt,name=breaker,proto3" json:"breaker,omitempty"`
	// MISSING DOCUMENTATION!!!
	BreakerDiscreteControl *BreakerDiscreteControl `protobuf:"bytes,3,opt,name=breakerDiscreteControl,proto3" json:"breakerDiscreteControl,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BreakerDiscreteControlProfile) Reset()         { *m = BreakerDiscreteControlProfile{} }
func (m *BreakerDiscreteControlProfile) String() string { return proto.CompactTextString(m) }
func (*BreakerDiscreteControlProfile) ProtoMessage()    {}
func (*BreakerDiscreteControlProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{3}
}

func (m *BreakerDiscreteControlProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerDiscreteControlProfile.Unmarshal(m, b)
}
func (m *BreakerDiscreteControlProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerDiscreteControlProfile.Marshal(b, m, deterministic)
}
func (m *BreakerDiscreteControlProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerDiscreteControlProfile.Merge(m, src)
}
func (m *BreakerDiscreteControlProfile) XXX_Size() int {
	return xxx_messageInfo_BreakerDiscreteControlProfile.Size(m)
}
func (m *BreakerDiscreteControlProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerDiscreteControlProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerDiscreteControlProfile proto.InternalMessageInfo

func (m *BreakerDiscreteControlProfile) GetControlMessageInfo() *commonmodule.ControlMessageInfo {
	if m != nil {
		return m.ControlMessageInfo
	}
	return nil
}

func (m *BreakerDiscreteControlProfile) GetBreaker() *Breaker {
	if m != nil {
		return m.Breaker
	}
	return nil
}

func (m *BreakerDiscreteControlProfile) GetBreakerDiscreteControl() *BreakerDiscreteControl {
	if m != nil {
		return m.BreakerDiscreteControl
	}
	return nil
}

func (m *BreakerDiscreteControlProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// Breaker event class
type BreakerEvent struct {
	// UML inherited base object
	EventValue *commonmodule.EventValue `protobuf:"bytes,1,opt,name=eventValue,proto3" json:"eventValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	StatusAndEventXCBR   *commonmodule.StatusAndEventXCBR `protobuf:"bytes,2,opt,name=statusAndEventXCBR,proto3" json:"statusAndEventXCBR,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *BreakerEvent) Reset()         { *m = BreakerEvent{} }
func (m *BreakerEvent) String() string { return proto.CompactTextString(m) }
func (*BreakerEvent) ProtoMessage()    {}
func (*BreakerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{4}
}

func (m *BreakerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerEvent.Unmarshal(m, b)
}
func (m *BreakerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerEvent.Marshal(b, m, deterministic)
}
func (m *BreakerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerEvent.Merge(m, src)
}
func (m *BreakerEvent) XXX_Size() int {
	return xxx_messageInfo_BreakerEvent.Size(m)
}
func (m *BreakerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerEvent proto.InternalMessageInfo

func (m *BreakerEvent) GetEventValue() *commonmodule.EventValue {
	if m != nil {
		return m.EventValue
	}
	return nil
}

func (m *BreakerEvent) GetStatusAndEventXCBR() *commonmodule.StatusAndEventXCBR {
	if m != nil {
		return m.StatusAndEventXCBR
	}
	return nil
}

// Breaker event profile
type BreakerEventProfile struct {
	// UML inherited base object
	EventMessageInfo *commonmodule.EventMessageInfo `protobuf:"bytes,1,opt,name=eventMessageInfo,proto3" json:"eventMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Breaker *Breaker `protobuf:"bytes,2,opt,name=breaker,proto3" json:"breaker,omitempty"`
	// MISSING DOCUMENTATION!!!
	BreakerEvent *BreakerEvent `protobuf:"bytes,3,opt,name=breakerEvent,proto3" json:"breakerEvent,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BreakerEventProfile) Reset()         { *m = BreakerEventProfile{} }
func (m *BreakerEventProfile) String() string { return proto.CompactTextString(m) }
func (*BreakerEventProfile) ProtoMessage()    {}
func (*BreakerEventProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{5}
}

func (m *BreakerEventProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerEventProfile.Unmarshal(m, b)
}
func (m *BreakerEventProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerEventProfile.Marshal(b, m, deterministic)
}
func (m *BreakerEventProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerEventProfile.Merge(m, src)
}
func (m *BreakerEventProfile) XXX_Size() int {
	return xxx_messageInfo_BreakerEventProfile.Size(m)
}
func (m *BreakerEventProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerEventProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerEventProfile proto.InternalMessageInfo

func (m *BreakerEventProfile) GetEventMessageInfo() *commonmodule.EventMessageInfo {
	if m != nil {
		return m.EventMessageInfo
	}
	return nil
}

func (m *BreakerEventProfile) GetBreaker() *Breaker {
	if m != nil {
		return m.Breaker
	}
	return nil
}

func (m *BreakerEventProfile) GetBreakerEvent() *BreakerEvent {
	if m != nil {
		return m.BreakerEvent
	}
	return nil
}

func (m *BreakerEventProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// MISSING DOCUMENTATION!!!
type BreakerReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	DiffReadingMMXU *commonmodule.ReadingMMXU `protobuf:"bytes,2,opt,name=diffReadingMMXU,proto3" json:"diffReadingMMXU,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,3,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,4,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,5,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BreakerReading) Reset()         { *m = BreakerReading{} }
func (m *BreakerReading) String() string { return proto.CompactTextString(m) }
func (*BreakerReading) ProtoMessage()    {}
func (*BreakerReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{6}
}

func (m *BreakerReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerReading.Unmarshal(m, b)
}
func (m *BreakerReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerReading.Marshal(b, m, deterministic)
}
func (m *BreakerReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerReading.Merge(m, src)
}
func (m *BreakerReading) XXX_Size() int {
	return xxx_messageInfo_BreakerReading.Size(m)
}
func (m *BreakerReading) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerReading.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerReading proto.InternalMessageInfo

func (m *BreakerReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *BreakerReading) GetDiffReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.DiffReadingMMXU
	}
	return nil
}

func (m *BreakerReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *BreakerReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *BreakerReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Breaker reading profile
type BreakerReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Breaker *Breaker `protobuf:"bytes,2,opt,name=breaker,proto3" json:"breaker,omitempty"`
	// MISSING DOCUMENTATION!!!
	BreakerReading []*BreakerReading `protobuf:"bytes,3,rep,name=breakerReading,proto3" json:"breakerReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BreakerReadingProfile) Reset()         { *m = BreakerReadingProfile{} }
func (m *BreakerReadingProfile) String() string { return proto.CompactTextString(m) }
func (*BreakerReadingProfile) ProtoMessage()    {}
func (*BreakerReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{7}
}

func (m *BreakerReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerReadingProfile.Unmarshal(m, b)
}
func (m *BreakerReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerReadingProfile.Marshal(b, m, deterministic)
}
func (m *BreakerReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerReadingProfile.Merge(m, src)
}
func (m *BreakerReadingProfile) XXX_Size() int {
	return xxx_messageInfo_BreakerReadingProfile.Size(m)
}
func (m *BreakerReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerReadingProfile proto.InternalMessageInfo

func (m *BreakerReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *BreakerReadingProfile) GetBreaker() *Breaker {
	if m != nil {
		return m.Breaker
	}
	return nil
}

func (m *BreakerReadingProfile) GetBreakerReading() []*BreakerReading {
	if m != nil {
		return m.BreakerReading
	}
	return nil
}

func (m *BreakerReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// Status of a breaker
type BreakerStatus struct {
	// UML inherited base object
	StatusValue *commonmodule.StatusValue `protobuf:"bytes,1,opt,name=statusValue,proto3" json:"statusValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	StatusAndEventXCBR   *commonmodule.StatusAndEventXCBR `protobuf:"bytes,2,opt,name=statusAndEventXCBR,proto3" json:"statusAndEventXCBR,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *BreakerStatus) Reset()         { *m = BreakerStatus{} }
func (m *BreakerStatus) String() string { return proto.CompactTextString(m) }
func (*BreakerStatus) ProtoMessage()    {}
func (*BreakerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{8}
}

func (m *BreakerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerStatus.Unmarshal(m, b)
}
func (m *BreakerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerStatus.Marshal(b, m, deterministic)
}
func (m *BreakerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerStatus.Merge(m, src)
}
func (m *BreakerStatus) XXX_Size() int {
	return xxx_messageInfo_BreakerStatus.Size(m)
}
func (m *BreakerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerStatus proto.InternalMessageInfo

func (m *BreakerStatus) GetStatusValue() *commonmodule.StatusValue {
	if m != nil {
		return m.StatusValue
	}
	return nil
}

func (m *BreakerStatus) GetStatusAndEventXCBR() *commonmodule.StatusAndEventXCBR {
	if m != nil {
		return m.StatusAndEventXCBR
	}
	return nil
}

// Breaker status profile
type BreakerStatusProfile struct {
	// UML inherited base object
	StatusMessageInfo *commonmodule.StatusMessageInfo `protobuf:"bytes,1,opt,name=statusMessageInfo,proto3" json:"statusMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Breaker *Breaker `protobuf:"bytes,2,opt,name=breaker,proto3" json:"breaker,omitempty"`
	// MISSING DOCUMENTATION!!!
	BreakerStatus *BreakerStatus `protobuf:"bytes,3,opt,name=breakerStatus,proto3" json:"breakerStatus,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BreakerStatusProfile) Reset()         { *m = BreakerStatusProfile{} }
func (m *BreakerStatusProfile) String() string { return proto.CompactTextString(m) }
func (*BreakerStatusProfile) ProtoMessage()    {}
func (*BreakerStatusProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_da01caf3bb08bf38, []int{9}
}

func (m *BreakerStatusProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakerStatusProfile.Unmarshal(m, b)
}
func (m *BreakerStatusProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakerStatusProfile.Marshal(b, m, deterministic)
}
func (m *BreakerStatusProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakerStatusProfile.Merge(m, src)
}
func (m *BreakerStatusProfile) XXX_Size() int {
	return xxx_messageInfo_BreakerStatusProfile.Size(m)
}
func (m *BreakerStatusProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakerStatusProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BreakerStatusProfile proto.InternalMessageInfo

func (m *BreakerStatusProfile) GetStatusMessageInfo() *commonmodule.StatusMessageInfo {
	if m != nil {
		return m.StatusMessageInfo
	}
	return nil
}

func (m *BreakerStatusProfile) GetBreaker() *Breaker {
	if m != nil {
		return m.Breaker
	}
	return nil
}

func (m *BreakerStatusProfile) GetBreakerStatus() *BreakerStatus {
	if m != nil {
		return m.BreakerStatus
	}
	return nil
}

func (m *BreakerStatusProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func init() {
	proto.RegisterType((*BreakerDiscreteControlXCBR)(nil), "breakermodule.BreakerDiscreteControlXCBR")
	proto.RegisterType((*BreakerDiscreteControl)(nil), "breakermodule.BreakerDiscreteControl")
	proto.RegisterType((*Breaker)(nil), "breakermodule.Breaker")
	proto.RegisterType((*BreakerDiscreteControlProfile)(nil), "breakermodule.BreakerDiscreteControlProfile")
	proto.RegisterType((*BreakerEvent)(nil), "breakermodule.BreakerEvent")
	proto.RegisterType((*BreakerEventProfile)(nil), "breakermodule.BreakerEventProfile")
	proto.RegisterType((*BreakerReading)(nil), "breakermodule.BreakerReading")
	proto.RegisterType((*BreakerReadingProfile)(nil), "breakermodule.BreakerReadingProfile")
	proto.RegisterType((*BreakerStatus)(nil), "breakermodule.BreakerStatus")
	proto.RegisterType((*BreakerStatusProfile)(nil), "breakermodule.BreakerStatusProfile")
}

func init() { proto.RegisterFile("breakermodule/breakermodule.proto", fileDescriptor_da01caf3bb08bf38) }

var fileDescriptor_da01caf3bb08bf38 = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x4f, 0xdb, 0x4a,
	0x14, 0x95, 0x1d, 0x78, 0x3c, 0x2e, 0x81, 0xf7, 0x18, 0x1e, 0x3c, 0x93, 0x96, 0x02, 0xae, 0x2a,
	0xb5, 0x8b, 0x90, 0xaa, 0xb4, 0x1b, 0x2a, 0x55, 0x22, 0x1f, 0x95, 0x90, 0x08, 0x4a, 0x4d, 0x40,
	0x94, 0x4d, 0xe5, 0x8f, 0x49, 0xb0, 0x70, 0x3c, 0xa9, 0x3f, 0xba, 0xee, 0xa2, 0xaa, 0xd8, 0xb5,
	0xcb, 0xee, 0xbb, 0x63, 0xd1, 0x4d, 0x95, 0x7d, 0xff, 0x42, 0x7f, 0x4b, 0xff, 0x40, 0x15, 0xfb,
	0x9a, 0xce, 0xc4, 0x93, 0x82, 0x40, 0xdd, 0xd9, 0x99, 0x73, 0xce, 0xbd, 0x73, 0xce, 0xcc, 0x8d,
	0x61, 0xdd, 0x0a, 0xa8, 0x79, 0x4a, 0x83, 0x1e, 0x73, 0x62, 0x8f, 0x56, 0x84, 0xb7, 0x8d, 0x7e,
	0xc0, 0x22, 0x46, 0x66, 0x85, 0x1f, 0x4b, 0xd3, 0x71, 0xcf, 0x4b, 0x57, 0x4a, 0xab, 0x36, 0xeb,
	0xf5, 0x98, 0x8f, 0x5c, 0xfe, 0x25, 0x05, 0xe8, 0x5f, 0x15, 0x28, 0x55, 0x53, 0x76, 0xdd, 0x0d,
	0xed, 0x80, 0x46, 0xb4, 0xc6, 0xfc, 0x28, 0x60, 0xde, 0x51, 0xad, 0x6a, 0x90, 0x57, 0xb0, 0xe8,
	0xb1, 0xae, 0x6b, 0x9b, 0xde, 0x1e, 0x73, 0xe8, 0x73, 0x16, 0xe0, 0xa2, 0xa6, 0xac, 0x29, 0xf7,
	0x67, 0x1e, 0xdd, 0xdd, 0x10, 0x24, 0x77, 0x65, 0xd0, 0xea, 0xc4, 0xdb, 0x81, 0xa6, 0x18, 0x72,
	0x1d, 0xf2, 0x18, 0x0a, 0x2d, 0x16, 0x6a, 0x6a, 0x22, 0xa7, 0x89, 0x72, 0x88, 0xa9, 0xb7, 0x6a,
	0xd5, 0xbf, 0xcf, 0x06, 0x9a, 0xf2, 0x71, 0xa8, 0x33, 0x84, 0xeb, 0x67, 0x2a, 0x2c, 0xc9, 0xbb,
	0x26, 0x75, 0x28, 0xda, 0xe9, 0xe3, 0xa1, 0xe9, 0xc5, 0x14, 0x1b, 0x2d, 0x49, 0x95, 0x13, 0x04,
	0xf6, 0x27, 0xb0, 0xc8, 0x26, 0x4c, 0xda, 0x27, 0xd4, 0x3e, 0xc5, 0xc6, 0x56, 0x46, 0xe8, 0xc3,
	0xa5, 0x1a, 0xf3, 0x1d, 0x37, 0x72, 0x99, 0x1f, 0x1a, 0x29, 0x96, 0x84, 0x50, 0xb2, 0xc6, 0x5a,
	0xa9, 0x15, 0x12, 0xa5, 0x07, 0x1b, 0x62, 0x80, 0xe3, 0xbd, 0xe7, 0xf6, 0xfc, 0x1b, 0x59, 0xdd,
	0x81, 0x29, 0xd4, 0x20, 0x2f, 0x61, 0xc1, 0x66, 0xbe, 0x13, 0xdb, 0x91, 0xeb, 0x77, 0x1b, 0xaf,
	0x63, 0xb7, 0xdf, 0xa3, 0x7e, 0x84, 0x0e, 0xac, 0xe7, 0x1c, 0x18, 0x05, 0xa2, 0x11, 0x32, 0x0d,
	0xfd, 0xbb, 0x0a, 0x2b, 0xf2, 0x56, 0x5b, 0x01, 0xeb, 0xb8, 0x1e, 0x25, 0x87, 0x40, 0xd0, 0xc1,
	0x26, 0x0d, 0x43, 0xb3, 0x4b, 0x77, 0xfc, 0x0e, 0xc3, 0xda, 0x6b, 0x52, 0xf7, 0x39, 0x1c, 0x96,
	0x96, 0x28, 0x90, 0x2d, 0x98, 0xc2, 0xdd, 0x63, 0x16, 0x4b, 0x72, 0x07, 0x39, 0xbb, 0x32, 0x02,
	0xe9, 0xc2, 0x92, 0xdc, 0x39, 0x0c, 0xe3, 0xde, 0x95, 0xc2, 0xe0, 0x94, 0xc7, 0xc8, 0x91, 0x32,
	0x14, 0x5c, 0xea, 0x68, 0x13, 0x89, 0xea, 0xbc, 0xb8, 0xdb, 0x9d, 0x46, 0x9d, 0x3f, 0xbe, 0x2e,
	0x75, 0xb6, 0x26, 0xbe, 0xfd, 0xd0, 0x14, 0xfd, 0x5c, 0x81, 0x22, 0x56, 0x6c, 0xbc, 0xa1, 0x7e,
	0x44, 0x9e, 0x01, 0xd0, 0xe1, 0x03, 0x7f, 0x70, 0x47, 0xae, 0x44, 0xe3, 0x62, 0x1d, 0x2d, 0xe3,
	0x18, 0xe4, 0x18, 0x48, 0x18, 0x99, 0x51, 0x1c, 0x6e, 0xfb, 0x4e, 0x02, 0x4c, 0xce, 0x9d, 0x2a,
	0x8b, 0x60, 0x3f, 0x87, 0xe3, 0x7a, 0x94, 0xa8, 0xe8, 0x9f, 0x55, 0x58, 0xe0, 0x9b, 0xcd, 0x62,
	0x6f, 0xc1, 0xbf, 0x49, 0x07, 0xf9, 0xd0, 0xef, 0x48, 0x3a, 0xcf, 0x47, 0x9e, 0x63, 0xdf, 0x28,
	0xf0, 0x1d, 0x28, 0x5a, 0x5c, 0x93, 0x18, 0xf3, 0x2d, 0xb9, 0x40, 0x02, 0xe1, 0x54, 0x04, 0xea,
	0xf5, 0x22, 0xfd, 0x50, 0x80, 0x39, 0x54, 0x37, 0xa8, 0xe9, 0xb8, 0x7e, 0x97, 0xbc, 0x57, 0x40,
	0x97, 0xdc, 0xa8, 0x36, 0x0d, 0x7a, 0xae, 0x6f, 0x7a, 0x08, 0x43, 0xcf, 0x1e, 0x5e, 0x7a, 0x49,
	0x47, 0x78, 0xe8, 0xe2, 0x15, 0x2a, 0x90, 0x1a, 0xfc, 0xe3, 0xb8, 0x9d, 0x0e, 0xbe, 0x36, 0x9b,
	0x47, 0x07, 0xe8, 0xef, 0xb2, 0x58, 0x94, 0x03, 0x18, 0xa3, 0x0c, 0xf2, 0x04, 0xa6, 0xfb, 0x27,
	0x66, 0x48, 0x9b, 0xcd, 0xf6, 0x1e, 0xba, 0xfb, 0xbf, 0x48, 0x6f, 0x65, 0xcb, 0xc6, 0x2f, 0x24,
	0x79, 0x0a, 0x33, 0x41, 0xa6, 0xd2, 0x36, 0xd0, 0xd4, 0x71, 0x75, 0xdb, 0x86, 0xc1, 0xa3, 0x05,
	0xf2, 0xd1, 0x81, 0x36, 0x79, 0x59, 0xd3, 0x3c, 0x5a, 0x1f, 0xa8, 0xb0, 0x28, 0x26, 0xc2, 0x0d,
	0xac, 0x0c, 0x78, 0xd9, 0xc0, 0x32, 0x72, 0xb8, 0x6c, 0x60, 0xe5, 0x15, 0x6e, 0x74, 0x7e, 0xf7,
	0x61, 0xce, 0x12, 0x9a, 0xd5, 0x0a, 0x6b, 0x85, 0xe4, 0xff, 0x47, 0x2a, 0x91, 0x1d, 0x82, 0x62,
	0xa6, 0xf4, 0x69, 0xa0, 0xa9, 0xc6, 0x88, 0xc4, 0xf5, 0x4e, 0xf2, 0x17, 0x05, 0x66, 0xb1, 0x4a,
	0x3a, 0x2b, 0xc8, 0x36, 0xcc, 0xa4, 0x73, 0x81, 0x1f, 0x4f, 0xcb, 0xb2, 0xb1, 0xc2, 0xcf, 0x27,
	0x9e, 0xf3, 0x47, 0x07, 0xd4, 0xb9, 0x0a, 0xff, 0x09, 0x0d, 0x67, 0x39, 0xef, 0xc3, 0x7c, 0x0a,
	0xcf, 0xc7, 0xbc, 0x2a, 0xab, 0x99, 0x4f, 0x39, 0xcf, 0xbf, 0x51, 0xc8, 0xbb, 0x90, 0x7d, 0xaf,
	0xa5, 0x05, 0xf1, 0x1e, 0xdd, 0x96, 0x2b, 0xa4, 0x18, 0x4e, 0x47, 0x24, 0x5f, 0x2b, 0xdd, 0xea,
	0x3b, 0x05, 0x16, 0x59, 0x9f, 0xfa, 0x9d, 0x9e, 0x25, 0x56, 0x6d, 0x29, 0xc7, 0x2f, 0xba, 0x6e,
	0xe4, 0x99, 0xd6, 0x50, 0xa9, 0x82, 0x98, 0x4a, 0x3f, 0x1c, 0x3e, 0x87, 0x95, 0xe4, 0x9b, 0xd1,
	0x8a, 0x3b, 0x95, 0x2e, 0x2b, 0xe3, 0x5a, 0x99, 0xf5, 0xc3, 0xf2, 0xc5, 0xef, 0x19, 0x41, 0x10,
	0x3d, 0x57, 0xe5, 0xc5, 0xac, 0xbf, 0x12, 0xde, 0xe6, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0x25, 0x4b, 0xa4, 0xe3, 0x0a, 0x00, 0x00,
}
