// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loadmodule/loadmodule.proto

package loadmodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Point definition (Point)
type LoadPoint struct {
	// Ramp rates
	RampRates *commonmodule.RampRate `protobuf:"bytes,1,opt,name=rampRates,proto3" json:"rampRates,omitempty"`
	// Enable reactive power set point
	ReactivePwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=reactivePwrSetPointEnabled,proto3" json:"reactivePwrSetPointEnabled,omitempty"`
	// Enable joint real power set point
	RealPwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,3,opt,name=realPwrSetPointEnabled,proto3" json:"realPwrSetPointEnabled,omitempty"`
	// Reset device
	Reset_ *commonmodule.ControlDPC `protobuf:"bytes,4,opt,name=reset,proto3" json:"reset,omitempty"`
	// ESS state
	State *commonmodule.Optional_StateKind `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Start time
	StartTime            *commonmodule.ControlTimestamp `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *LoadPoint) Reset()         { *m = LoadPoint{} }
func (m *LoadPoint) String() string { return proto.CompactTextString(m) }
func (*LoadPoint) ProtoMessage()    {}
func (*LoadPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{0}
}

func (m *LoadPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPoint.Unmarshal(m, b)
}
func (m *LoadPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPoint.Marshal(b, m, deterministic)
}
func (m *LoadPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPoint.Merge(m, src)
}
func (m *LoadPoint) XXX_Size() int {
	return xxx_messageInfo_LoadPoint.Size(m)
}
func (m *LoadPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPoint.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPoint proto.InternalMessageInfo

func (m *LoadPoint) GetRampRates() *commonmodule.RampRate {
	if m != nil {
		return m.RampRates
	}
	return nil
}

func (m *LoadPoint) GetReactivePwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.ReactivePwrSetPointEnabled
	}
	return nil
}

func (m *LoadPoint) GetRealPwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.RealPwrSetPointEnabled
	}
	return nil
}

func (m *LoadPoint) GetReset_() *commonmodule.ControlDPC {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func (m *LoadPoint) GetState() *commonmodule.Optional_StateKind {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *LoadPoint) GetStartTime() *commonmodule.ControlTimestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

// Curve shape setting (FC=SP) (CSG_SP)
type LoadCSG struct {
	// The array with the points specifying a curve shape.
	CrvPts               []*LoadPoint `protobuf:"bytes,1,rep,name=crvPts,proto3" json:"crvPts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoadCSG) Reset()         { *m = LoadCSG{} }
func (m *LoadCSG) String() string { return proto.CompactTextString(m) }
func (*LoadCSG) ProtoMessage()    {}
func (*LoadCSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{1}
}

func (m *LoadCSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCSG.Unmarshal(m, b)
}
func (m *LoadCSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCSG.Marshal(b, m, deterministic)
}
func (m *LoadCSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCSG.Merge(m, src)
}
func (m *LoadCSG) XXX_Size() int {
	return xxx_messageInfo_LoadCSG.Size(m)
}
func (m *LoadCSG) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCSG.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCSG proto.InternalMessageInfo

func (m *LoadCSG) GetCrvPts() []*LoadPoint {
	if m != nil {
		return m.CrvPts
	}
	return nil
}

// OpenFMB specialization for control schedule using:  LN: Schedule   Name: FSCH
type LoadControlScheduleFSCH struct {
	// Discrete value in LoadCSG type
	ValDCSG              *LoadCSG `protobuf:"bytes,1,opt,name=ValDCSG,proto3" json:"ValDCSG,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadControlScheduleFSCH) Reset()         { *m = LoadControlScheduleFSCH{} }
func (m *LoadControlScheduleFSCH) String() string { return proto.CompactTextString(m) }
func (*LoadControlScheduleFSCH) ProtoMessage()    {}
func (*LoadControlScheduleFSCH) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{2}
}

func (m *LoadControlScheduleFSCH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadControlScheduleFSCH.Unmarshal(m, b)
}
func (m *LoadControlScheduleFSCH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadControlScheduleFSCH.Marshal(b, m, deterministic)
}
func (m *LoadControlScheduleFSCH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadControlScheduleFSCH.Merge(m, src)
}
func (m *LoadControlScheduleFSCH) XXX_Size() int {
	return xxx_messageInfo_LoadControlScheduleFSCH.Size(m)
}
func (m *LoadControlScheduleFSCH) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadControlScheduleFSCH.DiscardUnknown(m)
}

var xxx_messageInfo_LoadControlScheduleFSCH proto.InternalMessageInfo

func (m *LoadControlScheduleFSCH) GetValDCSG() *LoadCSG {
	if m != nil {
		return m.ValDCSG
	}
	return nil
}

// Specialized FSCC 61850 class.  LN: Schedule controller   Name: FSCC
type LoadControlFSCC struct {
	// UML inherited base object
	ControlFSCC *commonmodule.ControlFSCC `protobuf:"bytes,1,opt,name=controlFSCC,proto3" json:"controlFSCC,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadControlScheduleFSCH *LoadControlScheduleFSCH `protobuf:"bytes,2,opt,name=loadControlScheduleFSCH,proto3" json:"loadControlScheduleFSCH,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *LoadControlFSCC) Reset()         { *m = LoadControlFSCC{} }
func (m *LoadControlFSCC) String() string { return proto.CompactTextString(m) }
func (*LoadControlFSCC) ProtoMessage()    {}
func (*LoadControlFSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{3}
}

func (m *LoadControlFSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadControlFSCC.Unmarshal(m, b)
}
func (m *LoadControlFSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadControlFSCC.Marshal(b, m, deterministic)
}
func (m *LoadControlFSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadControlFSCC.Merge(m, src)
}
func (m *LoadControlFSCC) XXX_Size() int {
	return xxx_messageInfo_LoadControlFSCC.Size(m)
}
func (m *LoadControlFSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadControlFSCC.DiscardUnknown(m)
}

var xxx_messageInfo_LoadControlFSCC proto.InternalMessageInfo

func (m *LoadControlFSCC) GetControlFSCC() *commonmodule.ControlFSCC {
	if m != nil {
		return m.ControlFSCC
	}
	return nil
}

func (m *LoadControlFSCC) GetLoadControlScheduleFSCH() *LoadControlScheduleFSCH {
	if m != nil {
		return m.LoadControlScheduleFSCH
	}
	return nil
}

// Load control
type LoadControl struct {
	// UML inherited base object
	ControlValue *commonmodule.ControlValue `protobuf:"bytes,1,opt,name=controlValue,proto3" json:"controlValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	Check *commonmodule.CheckConditions `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadControlFSCC      *LoadControlFSCC `protobuf:"bytes,3,opt,name=loadControlFSCC,proto3" json:"loadControlFSCC,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoadControl) Reset()         { *m = LoadControl{} }
func (m *LoadControl) String() string { return proto.CompactTextString(m) }
func (*LoadControl) ProtoMessage()    {}
func (*LoadControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{4}
}

func (m *LoadControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadControl.Unmarshal(m, b)
}
func (m *LoadControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadControl.Marshal(b, m, deterministic)
}
func (m *LoadControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadControl.Merge(m, src)
}
func (m *LoadControl) XXX_Size() int {
	return xxx_messageInfo_LoadControl.Size(m)
}
func (m *LoadControl) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadControl.DiscardUnknown(m)
}

var xxx_messageInfo_LoadControl proto.InternalMessageInfo

func (m *LoadControl) GetControlValue() *commonmodule.ControlValue {
	if m != nil {
		return m.ControlValue
	}
	return nil
}

func (m *LoadControl) GetCheck() *commonmodule.CheckConditions {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *LoadControl) GetLoadControlFSCC() *LoadControlFSCC {
	if m != nil {
		return m.LoadControlFSCC
	}
	return nil
}

// Load control profile
type LoadControlProfile struct {
	// UML inherited base object
	ControlMessageInfo *commonmodule.ControlMessageInfo `protobuf:"bytes,1,opt,name=controlMessageInfo,proto3" json:"controlMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	EnergyConsumer *commonmodule.EnergyConsumer `protobuf:"bytes,2,opt,name=energyConsumer,proto3" json:"energyConsumer,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadControl          *LoadControl `protobuf:"bytes,4,opt,name=loadControl,proto3" json:"loadControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoadControlProfile) Reset()         { *m = LoadControlProfile{} }
func (m *LoadControlProfile) String() string { return proto.CompactTextString(m) }
func (*LoadControlProfile) ProtoMessage()    {}
func (*LoadControlProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{5}
}

func (m *LoadControlProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadControlProfile.Unmarshal(m, b)
}
func (m *LoadControlProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadControlProfile.Marshal(b, m, deterministic)
}
func (m *LoadControlProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadControlProfile.Merge(m, src)
}
func (m *LoadControlProfile) XXX_Size() int {
	return xxx_messageInfo_LoadControlProfile.Size(m)
}
func (m *LoadControlProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadControlProfile.DiscardUnknown(m)
}

var xxx_messageInfo_LoadControlProfile proto.InternalMessageInfo

func (m *LoadControlProfile) GetControlMessageInfo() *commonmodule.ControlMessageInfo {
	if m != nil {
		return m.ControlMessageInfo
	}
	return nil
}

func (m *LoadControlProfile) GetEnergyConsumer() *commonmodule.EnergyConsumer {
	if m != nil {
		return m.EnergyConsumer
	}
	return nil
}

func (m *LoadControlProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *LoadControlProfile) GetLoadControl() *LoadControl {
	if m != nil {
		return m.LoadControl
	}
	return nil
}

// Point definition (Point)
type LoadPointStatus struct {
	// Ramp rates
	RampRates *commonmodule.RampRate `protobuf:"bytes,1,opt,name=rampRates,proto3" json:"rampRates,omitempty"`
	// Enable reactive power set point
	ReactivePwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=reactivePwrSetPointEnabled,proto3" json:"reactivePwrSetPointEnabled,omitempty"`
	// Enable joint real power set point
	RealPwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,3,opt,name=realPwrSetPointEnabled,proto3" json:"realPwrSetPointEnabled,omitempty"`
	// Reset device
	Reset_ *commonmodule.ControlDPC `protobuf:"bytes,4,opt,name=reset,proto3" json:"reset,omitempty"`
	// ESS state
	State                *commonmodule.Optional_StateKind `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LoadPointStatus) Reset()         { *m = LoadPointStatus{} }
func (m *LoadPointStatus) String() string { return proto.CompactTextString(m) }
func (*LoadPointStatus) ProtoMessage()    {}
func (*LoadPointStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{6}
}

func (m *LoadPointStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPointStatus.Unmarshal(m, b)
}
func (m *LoadPointStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPointStatus.Marshal(b, m, deterministic)
}
func (m *LoadPointStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPointStatus.Merge(m, src)
}
func (m *LoadPointStatus) XXX_Size() int {
	return xxx_messageInfo_LoadPointStatus.Size(m)
}
func (m *LoadPointStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPointStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPointStatus proto.InternalMessageInfo

func (m *LoadPointStatus) GetRampRates() *commonmodule.RampRate {
	if m != nil {
		return m.RampRates
	}
	return nil
}

func (m *LoadPointStatus) GetReactivePwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.ReactivePwrSetPointEnabled
	}
	return nil
}

func (m *LoadPointStatus) GetRealPwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.RealPwrSetPointEnabled
	}
	return nil
}

func (m *LoadPointStatus) GetReset_() *commonmodule.ControlDPC {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func (m *LoadPointStatus) GetState() *commonmodule.Optional_StateKind {
	if m != nil {
		return m.State
	}
	return nil
}

// Specialized 61850 ZGLD class
type LoadEventAndStatusZGLD struct {
	// UML inherited base object
	LogicalNodeForEventAndStatus *commonmodule.LogicalNodeForEventAndStatus `protobuf:"bytes,1,opt,name=logicalNodeForEventAndStatus,proto3" json:"logicalNodeForEventAndStatus,omitempty"`
	// MISSING DOCUMENTATION!!!
	DynamicTest *commonmodule.ENS_DynamicTestKind `protobuf:"bytes,2,opt,name=DynamicTest,proto3" json:"DynamicTest,omitempty"`
	// Emergency stop
	EmgStop *commonmodule.StatusSPS `protobuf:"bytes,3,opt,name=EmgStop,proto3" json:"EmgStop,omitempty"`
	// Point status
	PointStatus          *LoadPointStatus `protobuf:"bytes,4,opt,name=PointStatus,proto3" json:"PointStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoadEventAndStatusZGLD) Reset()         { *m = LoadEventAndStatusZGLD{} }
func (m *LoadEventAndStatusZGLD) String() string { return proto.CompactTextString(m) }
func (*LoadEventAndStatusZGLD) ProtoMessage()    {}
func (*LoadEventAndStatusZGLD) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{7}
}

func (m *LoadEventAndStatusZGLD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadEventAndStatusZGLD.Unmarshal(m, b)
}
func (m *LoadEventAndStatusZGLD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadEventAndStatusZGLD.Marshal(b, m, deterministic)
}
func (m *LoadEventAndStatusZGLD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadEventAndStatusZGLD.Merge(m, src)
}
func (m *LoadEventAndStatusZGLD) XXX_Size() int {
	return xxx_messageInfo_LoadEventAndStatusZGLD.Size(m)
}
func (m *LoadEventAndStatusZGLD) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadEventAndStatusZGLD.DiscardUnknown(m)
}

var xxx_messageInfo_LoadEventAndStatusZGLD proto.InternalMessageInfo

func (m *LoadEventAndStatusZGLD) GetLogicalNodeForEventAndStatus() *commonmodule.LogicalNodeForEventAndStatus {
	if m != nil {
		return m.LogicalNodeForEventAndStatus
	}
	return nil
}

func (m *LoadEventAndStatusZGLD) GetDynamicTest() *commonmodule.ENS_DynamicTestKind {
	if m != nil {
		return m.DynamicTest
	}
	return nil
}

func (m *LoadEventAndStatusZGLD) GetEmgStop() *commonmodule.StatusSPS {
	if m != nil {
		return m.EmgStop
	}
	return nil
}

func (m *LoadEventAndStatusZGLD) GetPointStatus() *LoadPointStatus {
	if m != nil {
		return m.PointStatus
	}
	return nil
}

// Specialized 61850 ZGLD LN class
type LoadEventZGLD struct {
	// UML inherited base object
	LoadEventAndStatusZGLD *LoadEventAndStatusZGLD `protobuf:"bytes,1,opt,name=loadEventAndStatusZGLD,proto3" json:"loadEventAndStatusZGLD,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *LoadEventZGLD) Reset()         { *m = LoadEventZGLD{} }
func (m *LoadEventZGLD) String() string { return proto.CompactTextString(m) }
func (*LoadEventZGLD) ProtoMessage()    {}
func (*LoadEventZGLD) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{8}
}

func (m *LoadEventZGLD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadEventZGLD.Unmarshal(m, b)
}
func (m *LoadEventZGLD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadEventZGLD.Marshal(b, m, deterministic)
}
func (m *LoadEventZGLD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadEventZGLD.Merge(m, src)
}
func (m *LoadEventZGLD) XXX_Size() int {
	return xxx_messageInfo_LoadEventZGLD.Size(m)
}
func (m *LoadEventZGLD) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadEventZGLD.DiscardUnknown(m)
}

var xxx_messageInfo_LoadEventZGLD proto.InternalMessageInfo

func (m *LoadEventZGLD) GetLoadEventAndStatusZGLD() *LoadEventAndStatusZGLD {
	if m != nil {
		return m.LoadEventAndStatusZGLD
	}
	return nil
}

// Load event
type LoadEvent struct {
	// UML inherited base object
	EventValue *commonmodule.EventValue `protobuf:"bytes,1,opt,name=eventValue,proto3" json:"eventValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadEventZGLD        *LoadEventZGLD `protobuf:"bytes,2,opt,name=loadEventZGLD,proto3" json:"loadEventZGLD,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LoadEvent) Reset()         { *m = LoadEvent{} }
func (m *LoadEvent) String() string { return proto.CompactTextString(m) }
func (*LoadEvent) ProtoMessage()    {}
func (*LoadEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{9}
}

func (m *LoadEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadEvent.Unmarshal(m, b)
}
func (m *LoadEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadEvent.Marshal(b, m, deterministic)
}
func (m *LoadEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadEvent.Merge(m, src)
}
func (m *LoadEvent) XXX_Size() int {
	return xxx_messageInfo_LoadEvent.Size(m)
}
func (m *LoadEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LoadEvent proto.InternalMessageInfo

func (m *LoadEvent) GetEventValue() *commonmodule.EventValue {
	if m != nil {
		return m.EventValue
	}
	return nil
}

func (m *LoadEvent) GetLoadEventZGLD() *LoadEventZGLD {
	if m != nil {
		return m.LoadEventZGLD
	}
	return nil
}

// Load event profile
type LoadEventProfile struct {
	// UML inherited base object
	EventMessageInfo *commonmodule.EventMessageInfo `protobuf:"bytes,1,opt,name=eventMessageInfo,proto3" json:"eventMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	EnergyConsumer *commonmodule.EnergyConsumer `protobuf:"bytes,2,opt,name=energyConsumer,proto3" json:"energyConsumer,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadEvent            *LoadEvent `protobuf:"bytes,4,opt,name=loadEvent,proto3" json:"loadEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoadEventProfile) Reset()         { *m = LoadEventProfile{} }
func (m *LoadEventProfile) String() string { return proto.CompactTextString(m) }
func (*LoadEventProfile) ProtoMessage()    {}
func (*LoadEventProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{10}
}

func (m *LoadEventProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadEventProfile.Unmarshal(m, b)
}
func (m *LoadEventProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadEventProfile.Marshal(b, m, deterministic)
}
func (m *LoadEventProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadEventProfile.Merge(m, src)
}
func (m *LoadEventProfile) XXX_Size() int {
	return xxx_messageInfo_LoadEventProfile.Size(m)
}
func (m *LoadEventProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadEventProfile.DiscardUnknown(m)
}

var xxx_messageInfo_LoadEventProfile proto.InternalMessageInfo

func (m *LoadEventProfile) GetEventMessageInfo() *commonmodule.EventMessageInfo {
	if m != nil {
		return m.EventMessageInfo
	}
	return nil
}

func (m *LoadEventProfile) GetEnergyConsumer() *commonmodule.EnergyConsumer {
	if m != nil {
		return m.EnergyConsumer
	}
	return nil
}

func (m *LoadEventProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *LoadEventProfile) GetLoadEvent() *LoadEvent {
	if m != nil {
		return m.LoadEvent
	}
	return nil
}

// Load reading value
type LoadReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,2,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,3,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,4,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LoadReading) Reset()         { *m = LoadReading{} }
func (m *LoadReading) String() string { return proto.CompactTextString(m) }
func (*LoadReading) ProtoMessage()    {}
func (*LoadReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{11}
}

func (m *LoadReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadReading.Unmarshal(m, b)
}
func (m *LoadReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadReading.Marshal(b, m, deterministic)
}
func (m *LoadReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadReading.Merge(m, src)
}
func (m *LoadReading) XXX_Size() int {
	return xxx_messageInfo_LoadReading.Size(m)
}
func (m *LoadReading) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadReading.DiscardUnknown(m)
}

var xxx_messageInfo_LoadReading proto.InternalMessageInfo

func (m *LoadReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *LoadReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *LoadReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *LoadReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Load reading profile
type LoadReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	EnergyConsumer *commonmodule.EnergyConsumer `protobuf:"bytes,2,opt,name=energyConsumer,proto3" json:"energyConsumer,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadReading          *LoadReading `protobuf:"bytes,4,opt,name=loadReading,proto3" json:"loadReading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoadReadingProfile) Reset()         { *m = LoadReadingProfile{} }
func (m *LoadReadingProfile) String() string { return proto.CompactTextString(m) }
func (*LoadReadingProfile) ProtoMessage()    {}
func (*LoadReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{12}
}

func (m *LoadReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadReadingProfile.Unmarshal(m, b)
}
func (m *LoadReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadReadingProfile.Marshal(b, m, deterministic)
}
func (m *LoadReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadReadingProfile.Merge(m, src)
}
func (m *LoadReadingProfile) XXX_Size() int {
	return xxx_messageInfo_LoadReadingProfile.Size(m)
}
func (m *LoadReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_LoadReadingProfile proto.InternalMessageInfo

func (m *LoadReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *LoadReadingProfile) GetEnergyConsumer() *commonmodule.EnergyConsumer {
	if m != nil {
		return m.EnergyConsumer
	}
	return nil
}

func (m *LoadReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *LoadReadingProfile) GetLoadReading() *LoadReading {
	if m != nil {
		return m.LoadReading
	}
	return nil
}

// Specialized 61850 ZGLD LN class
type LoadStatusZGLD struct {
	// UML inherited base object
	LoadEventAndStatusZGLD *LoadEventAndStatusZGLD `protobuf:"bytes,1,opt,name=loadEventAndStatusZGLD,proto3" json:"loadEventAndStatusZGLD,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *LoadStatusZGLD) Reset()         { *m = LoadStatusZGLD{} }
func (m *LoadStatusZGLD) String() string { return proto.CompactTextString(m) }
func (*LoadStatusZGLD) ProtoMessage()    {}
func (*LoadStatusZGLD) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{13}
}

func (m *LoadStatusZGLD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadStatusZGLD.Unmarshal(m, b)
}
func (m *LoadStatusZGLD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadStatusZGLD.Marshal(b, m, deterministic)
}
func (m *LoadStatusZGLD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadStatusZGLD.Merge(m, src)
}
func (m *LoadStatusZGLD) XXX_Size() int {
	return xxx_messageInfo_LoadStatusZGLD.Size(m)
}
func (m *LoadStatusZGLD) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadStatusZGLD.DiscardUnknown(m)
}

var xxx_messageInfo_LoadStatusZGLD proto.InternalMessageInfo

func (m *LoadStatusZGLD) GetLoadEventAndStatusZGLD() *LoadEventAndStatusZGLD {
	if m != nil {
		return m.LoadEventAndStatusZGLD
	}
	return nil
}

// Load status
type LoadStatus struct {
	// UML inherited base object
	StatusValue *commonmodule.StatusValue `protobuf:"bytes,1,opt,name=statusValue,proto3" json:"statusValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadStatusZGLD       *LoadStatusZGLD `protobuf:"bytes,2,opt,name=loadStatusZGLD,proto3" json:"loadStatusZGLD,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoadStatus) Reset()         { *m = LoadStatus{} }
func (m *LoadStatus) String() string { return proto.CompactTextString(m) }
func (*LoadStatus) ProtoMessage()    {}
func (*LoadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{14}
}

func (m *LoadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadStatus.Unmarshal(m, b)
}
func (m *LoadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadStatus.Marshal(b, m, deterministic)
}
func (m *LoadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadStatus.Merge(m, src)
}
func (m *LoadStatus) XXX_Size() int {
	return xxx_messageInfo_LoadStatus.Size(m)
}
func (m *LoadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LoadStatus proto.InternalMessageInfo

func (m *LoadStatus) GetStatusValue() *commonmodule.StatusValue {
	if m != nil {
		return m.StatusValue
	}
	return nil
}

func (m *LoadStatus) GetLoadStatusZGLD() *LoadStatusZGLD {
	if m != nil {
		return m.LoadStatusZGLD
	}
	return nil
}

// Load status profile
type LoadStatusProfile struct {
	// UML inherited base object
	StatusMessageInfo *commonmodule.StatusMessageInfo `protobuf:"bytes,1,opt,name=statusMessageInfo,proto3" json:"statusMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	EnergyConsumer *commonmodule.EnergyConsumer `protobuf:"bytes,2,opt,name=energyConsumer,proto3" json:"energyConsumer,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	LoadStatus           *LoadStatus `protobuf:"bytes,4,opt,name=loadStatus,proto3" json:"loadStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoadStatusProfile) Reset()         { *m = LoadStatusProfile{} }
func (m *LoadStatusProfile) String() string { return proto.CompactTextString(m) }
func (*LoadStatusProfile) ProtoMessage()    {}
func (*LoadStatusProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_708c8dadcbf9c198, []int{15}
}

func (m *LoadStatusProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadStatusProfile.Unmarshal(m, b)
}
func (m *LoadStatusProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadStatusProfile.Marshal(b, m, deterministic)
}
func (m *LoadStatusProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadStatusProfile.Merge(m, src)
}
func (m *LoadStatusProfile) XXX_Size() int {
	return xxx_messageInfo_LoadStatusProfile.Size(m)
}
func (m *LoadStatusProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadStatusProfile.DiscardUnknown(m)
}

var xxx_messageInfo_LoadStatusProfile proto.InternalMessageInfo

func (m *LoadStatusProfile) GetStatusMessageInfo() *commonmodule.StatusMessageInfo {
	if m != nil {
		return m.StatusMessageInfo
	}
	return nil
}

func (m *LoadStatusProfile) GetEnergyConsumer() *commonmodule.EnergyConsumer {
	if m != nil {
		return m.EnergyConsumer
	}
	return nil
}

func (m *LoadStatusProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *LoadStatusProfile) GetLoadStatus() *LoadStatus {
	if m != nil {
		return m.LoadStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*LoadPoint)(nil), "loadmodule.LoadPoint")
	proto.RegisterType((*LoadCSG)(nil), "loadmodule.LoadCSG")
	proto.RegisterType((*LoadControlScheduleFSCH)(nil), "loadmodule.LoadControlScheduleFSCH")
	proto.RegisterType((*LoadControlFSCC)(nil), "loadmodule.LoadControlFSCC")
	proto.RegisterType((*LoadControl)(nil), "loadmodule.LoadControl")
	proto.RegisterType((*LoadControlProfile)(nil), "loadmodule.LoadControlProfile")
	proto.RegisterType((*LoadPointStatus)(nil), "loadmodule.LoadPointStatus")
	proto.RegisterType((*LoadEventAndStatusZGLD)(nil), "loadmodule.LoadEventAndStatusZGLD")
	proto.RegisterType((*LoadEventZGLD)(nil), "loadmodule.LoadEventZGLD")
	proto.RegisterType((*LoadEvent)(nil), "loadmodule.LoadEvent")
	proto.RegisterType((*LoadEventProfile)(nil), "loadmodule.LoadEventProfile")
	proto.RegisterType((*LoadReading)(nil), "loadmodule.LoadReading")
	proto.RegisterType((*LoadReadingProfile)(nil), "loadmodule.LoadReadingProfile")
	proto.RegisterType((*LoadStatusZGLD)(nil), "loadmodule.LoadStatusZGLD")
	proto.RegisterType((*LoadStatus)(nil), "loadmodule.LoadStatus")
	proto.RegisterType((*LoadStatusProfile)(nil), "loadmodule.LoadStatusProfile")
}

func init() { proto.RegisterFile("loadmodule/loadmodule.proto", fileDescriptor_708c8dadcbf9c198) }

var fileDescriptor_708c8dadcbf9c198 = []byte{
	// 1093 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x4f, 0x6f, 0xdc, 0xd4,
	0x17, 0x95, 0x27, 0xff, 0x7e, 0x73, 0xe7, 0xd7, 0xb4, 0x79, 0xa8, 0xc9, 0x64, 0x52, 0xda, 0x60,
	0x36, 0x15, 0x52, 0x32, 0xd0, 0x02, 0x95, 0x40, 0x45, 0x34, 0x9e, 0x49, 0x88, 0xc8, 0x4c, 0x2d,
	0x7b, 0x1a, 0x45, 0x95, 0x50, 0x79, 0x63, 0xbf, 0x4c, 0x2c, 0x6c, 0x3f, 0xd7, 0x7e, 0x13, 0x54,
	0xb1, 0x61, 0x85, 0x58, 0xb2, 0x62, 0xd7, 0x3d, 0x62, 0xc3, 0x02, 0x95, 0x35, 0x1b, 0xc4, 0x67,
	0x40, 0x7c, 0x0c, 0xbe, 0x00, 0xb2, 0x7d, 0x3d, 0x7e, 0xfe, 0x33, 0x09, 0x0b, 0x50, 0x59, 0xb0,
	0xf3, 0xf8, 0x9d, 0x73, 0xde, 0xbd, 0xe7, 0xde, 0x77, 0x9f, 0x07, 0xb6, 0x5c, 0x4e, 0x6d, 0x8f,
	0xdb, 0x53, 0x97, 0x75, 0xf3, 0xc7, 0xdd, 0x20, 0xe4, 0x82, 0x13, 0xc8, 0xdf, 0x74, 0x9a, 0x53,
	0xcf, 0x4d, 0x5f, 0x77, 0x6e, 0x59, 0xdc, 0xf3, 0xb8, 0x8f, 0x2c, 0xf9, 0x47, 0x0a, 0x50, 0x9f,
	0x2f, 0x40, 0xf3, 0x88, 0x53, 0x5b, 0xe7, 0x8e, 0x2f, 0xc8, 0xdb, 0xd0, 0x0c, 0xa9, 0x17, 0x18,
	0x54, 0xb0, 0xa8, 0xad, 0x6c, 0x2b, 0xb7, 0x5b, 0x77, 0xd6, 0x77, 0x0b, 0x2c, 0x03, 0x97, 0x8d,
	0x1c, 0x48, 0x4e, 0xa0, 0x13, 0x32, 0x6a, 0x09, 0xe7, 0x9c, 0xe9, 0x9f, 0x87, 0x26, 0x13, 0x89,
	0x58, 0xdf, 0xa7, 0x63, 0x97, 0xd9, 0xed, 0x46, 0x22, 0xd3, 0x2e, 0xca, 0x68, 0xdc, 0x17, 0x21,
	0x77, 0x7b, 0xba, 0x66, 0x5c, 0xc0, 0x25, 0x3a, 0xac, 0x87, 0x8c, 0xba, 0x35, 0xaa, 0x0b, 0x97,
	0xa8, 0xce, 0xe1, 0x91, 0x5d, 0x58, 0x0a, 0x59, 0xc4, 0x44, 0x7b, 0xf1, 0x12, 0x81, 0x14, 0x46,
	0xde, 0x85, 0xa5, 0x48, 0x50, 0xc1, 0xda, 0x4b, 0x09, 0x7e, 0xbb, 0x88, 0x7f, 0x18, 0x08, 0x87,
	0xfb, 0xd4, 0x7d, 0x62, 0xc6, 0x98, 0x8f, 0x1d, 0xdf, 0x36, 0x52, 0x38, 0xd9, 0x87, 0x66, 0x24,
	0x68, 0x28, 0x46, 0x8e, 0xc7, 0xda, 0xcb, 0x09, 0xf7, 0x66, 0xed, 0x5e, 0x31, 0x20, 0x12, 0xd4,
	0x0b, 0xf6, 0xfe, 0xf7, 0xf5, 0x8b, 0xb6, 0xf2, 0xcd, 0x8b, 0xb6, 0x62, 0xe4, 0x54, 0x75, 0x0f,
	0x56, 0xe2, 0xf2, 0x68, 0xe6, 0x01, 0xb9, 0x07, 0xcb, 0x56, 0x78, 0xae, 0x8b, 0xb8, 0x32, 0x0b,
	0xb7, 0x5b, 0x77, 0xae, 0xef, 0x4a, 0x5d, 0x30, 0xab, 0xa1, 0x24, 0x83, 0x70, 0xd5, 0x80, 0x8d,
	0x44, 0x23, 0xdd, 0xd0, 0xb4, 0xce, 0x58, 0x4c, 0xd9, 0x37, 0xb5, 0x8f, 0xc8, 0x3d, 0x58, 0x39,
	0xa6, 0x6e, 0x4f, 0x33, 0x0f, 0xb0, 0xdc, 0xaf, 0x94, 0x45, 0x35, 0xf3, 0x40, 0x92, 0xcc, 0xd0,
	0xea, 0x8f, 0x0a, 0x5c, 0x95, 0x44, 0xf7, 0x4d, 0x4d, 0x23, 0x0f, 0xa0, 0x65, 0xe5, 0x3f, 0x51,
	0x70, 0xb3, 0x36, 0xeb, 0x18, 0xb0, 0xb7, 0xf8, 0x65, 0x2c, 0x29, 0x73, 0xc8, 0x27, 0xb0, 0xe1,
	0xd6, 0x87, 0x8a, 0x7d, 0xf4, 0x7a, 0x25, 0xbe, 0x2a, 0xd4, 0x98, 0xa7, 0xa1, 0xfe, 0xa6, 0x40,
	0x4b, 0x22, 0x91, 0x1e, 0xfc, 0x1f, 0x77, 0x3f, 0xa6, 0xee, 0x94, 0x61, 0xc8, 0x9d, 0xda, 0x90,
	0x13, 0x04, 0xc6, 0x5c, 0x60, 0x91, 0xbb, 0xb0, 0x64, 0x9d, 0x31, 0xeb, 0x33, 0x0c, 0xf1, 0xd5,
	0x12, 0x3d, 0x5e, 0xd2, 0xb8, 0x6f, 0x3b, 0x71, 0xaf, 0x44, 0x46, 0x8a, 0x25, 0x0f, 0xe1, 0xaa,
	0x5b, 0xf4, 0x0f, 0x7b, 0x7a, 0x6b, 0x4e, 0x86, 0x89, 0x65, 0x79, 0x25, 0xca, 0x6c, 0xf5, 0xa7,
	0x06, 0x10, 0x09, 0xae, 0x87, 0xfc, 0xd4, 0x71, 0x19, 0x39, 0x06, 0x82, 0xc1, 0x0e, 0x58, 0x14,
	0xd1, 0x09, 0x3b, 0xf4, 0x4f, 0x39, 0x26, 0xba, 0x5d, 0x9b, 0xa8, 0x84, 0xc3, 0x74, 0x6b, 0x14,
	0xc8, 0x10, 0x56, 0x99, 0xcf, 0xc2, 0xc9, 0x33, 0x8d, 0xfb, 0xd1, 0xd4, 0x63, 0x21, 0x66, 0x7f,
	0xa3, 0xa8, 0xd9, 0x2f, 0x60, 0xa4, 0xf8, 0x4b, 0x6c, 0xb2, 0x03, 0x0b, 0xce, 0xec, 0x5c, 0xaf,
	0x15, 0x45, 0x0e, 0xfb, 0x3d, 0x89, 0x19, 0xe3, 0x88, 0x06, 0x2d, 0xc9, 0x00, 0x3c, 0xcd, 0x1b,
	0x73, 0xac, 0x93, 0xc8, 0x32, 0xeb, 0xbd, 0xc5, 0x9f, 0xff, 0x68, 0x2b, 0xea, 0xef, 0x8d, 0xb4,
	0x95, 0x93, 0xe3, 0x13, 0x1f, 0xe4, 0x69, 0xf4, 0xdf, 0x20, 0xfc, 0xbb, 0x06, 0xa1, 0xfa, 0x4b,
	0x03, 0xd6, 0x63, 0x77, 0xfb, 0xe7, 0xcc, 0x17, 0x0f, 0x7c, 0x3b, 0x35, 0xf8, 0xf1, 0xc1, 0x51,
	0x8f, 0x08, 0xb8, 0xe1, 0xf2, 0x89, 0x63, 0x51, 0x77, 0xc8, 0x6d, 0xb6, 0xcf, 0xc3, 0x22, 0x06,
	0x7d, 0x7f, 0xa3, 0xb8, 0xd3, 0xd1, 0x05, 0x0c, 0x6c, 0xd7, 0x0b, 0x55, 0xe3, 0xce, 0xe9, 0x3d,
	0xf3, 0xa9, 0xe7, 0x58, 0x23, 0x16, 0x09, 0xac, 0xca, 0x6b, 0xa5, 0xae, 0x1d, 0x9a, 0x4f, 0x24,
	0x50, 0x92, 0x8f, 0xcc, 0x22, 0x6f, 0xc1, 0x4a, 0xdf, 0x9b, 0x98, 0x82, 0x07, 0x58, 0x80, 0x8d,
	0xa2, 0x40, 0xba, 0x97, 0xa9, 0x9b, 0x46, 0x86, 0x23, 0xf7, 0xa1, 0x25, 0x75, 0x18, 0xda, 0xbe,
	0x55, 0x3b, 0xc3, 0x53, 0x88, 0x21, 0xe3, 0xd5, 0xa7, 0x70, 0x65, 0x66, 0x63, 0xe2, 0xde, 0xa7,
	0xb0, 0xee, 0xd6, 0xfa, 0x8a, 0xbe, 0xa9, 0x65, 0xe9, 0x2a, 0x12, 0xfd, 0x9a, 0xa3, 0xa3, 0x7e,
	0xab, 0xa4, 0xdf, 0x06, 0xc9, 0x12, 0xf9, 0x00, 0x80, 0xc5, 0x0f, 0xf2, 0xa4, 0x2c, 0x75, 0x4d,
	0x7f, 0xb6, 0x8e, 0xca, 0x12, 0x83, 0x1c, 0xc2, 0x15, 0x57, 0x4e, 0x00, 0x9d, 0xdf, 0xac, 0x0d,
	0x33, 0x89, 0x2e, 0x3f, 0xb5, 0x45, 0xa6, 0xfa, 0x5d, 0x03, 0xae, 0xcd, 0xa0, 0xd9, 0xa0, 0xd3,
	0xe1, 0x5a, 0xb2, 0x5b, 0x75, 0xcc, 0xdd, 0xac, 0x89, 0xb2, 0x3a, 0xe4, 0x2a, 0xec, 0x97, 0x3d,
	0xe2, 0xee, 0x43, 0x73, 0x96, 0x36, 0xb6, 0xcb, 0xf5, 0x5a, 0xb3, 0xe4, 0x2f, 0x87, 0x19, 0x03,
	0x87, 0xdb, 0xaf, 0x8d, 0xf4, 0xc6, 0x33, 0x18, 0xb5, 0x1d, 0x7f, 0x42, 0xbe, 0x52, 0x40, 0xb5,
	0xb8, 0x6f, 0x4f, 0x2d, 0xe1, 0xf8, 0x93, 0xfe, 0xd3, 0xa9, 0x13, 0x78, 0xcc, 0x17, 0x23, 0x16,
	0x7a, 0x8e, 0x4f, 0x5d, 0x84, 0xa1, 0x71, 0x6f, 0x56, 0x86, 0xc2, 0x25, 0x3c, 0xb4, 0xf2, 0x2f,
	0xec, 0x40, 0xde, 0x81, 0x66, 0x70, 0x46, 0x23, 0x36, 0x18, 0x8c, 0x86, 0xe8, 0x6b, 0xe9, 0x0c,
	0xe9, 0xd9, 0xb2, 0x91, 0x23, 0xc9, 0xfb, 0xd0, 0x0a, 0x53, 0x85, 0xc1, 0x60, 0x64, 0xa0, 0x97,
	0xa5, 0x6f, 0x0c, 0x23, 0x07, 0x18, 0x32, 0xba, 0x40, 0x3e, 0x79, 0x84, 0x9e, 0xce, 0x23, 0x9f,
	0x3c, 0x32, 0x64, 0xf4, 0xec, 0x7e, 0x45, 0x80, 0x74, 0xbf, 0x66, 0xa8, 0xcb, 0xee, 0x57, 0xa3,
	0x82, 0xcb, 0xee, 0xd7, 0xaa, 0xc2, 0xbf, 0xe4, 0x7e, 0xcd, 0xfa, 0x61, 0xce, 0xfd, 0x9a, 0x95,
	0xbd, 0x74, 0xbf, 0xe2, 0x6b, 0x6c, 0xc1, 0x10, 0x56, 0x63, 0xac, 0x34, 0xf8, 0xff, 0xf9, 0xd1,
	0xf5, 0x5c, 0x01, 0xc8, 0x37, 0x8d, 0xbf, 0x4c, 0xa3, 0xe4, 0x49, 0x1e, 0x5e, 0x9b, 0x75, 0x23,
	0x5b, 0x9e, 0x5e, 0x32, 0x87, 0x1c, 0xc1, 0xaa, 0x5b, 0xc8, 0x02, 0xeb, 0xd1, 0x29, 0xc7, 0x2a,
	0xc5, 0x28, 0x55, 0xa3, 0xc8, 0x55, 0x7f, 0x68, 0xc0, 0x5a, 0x0e, 0xce, 0x7a, 0xc9, 0x84, 0xb5,
	0x74, 0xcb, 0x6a, 0x2b, 0xdd, 0xaa, 0x0b, 0xb6, 0xda, 0x49, 0x55, 0xfe, 0xcb, 0x6e, 0xa4, 0x0f,
	0x01, 0xf2, 0xdc, 0xb1, 0x8f, 0xd6, 0xeb, 0x3d, 0x93, 0xa8, 0x12, 0x27, 0xed, 0xa2, 0xbd, 0x2f,
	0x80, 0xf0, 0x80, 0xf9, 0xa7, 0xde, 0x58, 0x22, 0xeb, 0xca, 0xe3, 0xe1, 0xc4, 0x11, 0x2e, 0x1d,
	0xc7, 0x71, 0x74, 0x11, 0xd0, 0x0d, 0xa2, 0xf8, 0x39, 0xea, 0x26, 0x7f, 0x71, 0xc7, 0xd3, 0xd3,
	0xee, 0x84, 0xef, 0xe0, 0xda, 0x0e, 0x0f, 0xa2, 0x9d, 0xd9, 0xfb, 0x8c, 0x90, 0x2b, 0x7e, 0xdf,
	0xa8, 0xd9, 0x66, 0xbc, 0x9c, 0x30, 0xee, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x65, 0x0c,
	0xbe, 0x83, 0x0f, 0x00, 0x00,
}
