// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resourcemodule/resourcemodule.proto

package resourcemodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource reading value
type ResourceReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,2,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,3,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,4,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ResourceReading) Reset()         { *m = ResourceReading{} }
func (m *ResourceReading) String() string { return proto.CompactTextString(m) }
func (*ResourceReading) ProtoMessage()    {}
func (*ResourceReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfd19c4ccf8ab43, []int{0}
}

func (m *ResourceReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceReading.Unmarshal(m, b)
}
func (m *ResourceReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceReading.Marshal(b, m, deterministic)
}
func (m *ResourceReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceReading.Merge(m, src)
}
func (m *ResourceReading) XXX_Size() int {
	return xxx_messageInfo_ResourceReading.Size(m)
}
func (m *ResourceReading) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceReading.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceReading proto.InternalMessageInfo

func (m *ResourceReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *ResourceReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *ResourceReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *ResourceReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Resource reading profile
type ResourceReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	ConductingEquipment *commonmodule.ConductingEquipment `protobuf:"bytes,2,opt,name=conductingEquipment,proto3" json:"conductingEquipment,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	ResourceReading      *ResourceReading `protobuf:"bytes,4,opt,name=resourceReading,proto3" json:"resourceReading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResourceReadingProfile) Reset()         { *m = ResourceReadingProfile{} }
func (m *ResourceReadingProfile) String() string { return proto.CompactTextString(m) }
func (*ResourceReadingProfile) ProtoMessage()    {}
func (*ResourceReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfd19c4ccf8ab43, []int{1}
}

func (m *ResourceReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceReadingProfile.Unmarshal(m, b)
}
func (m *ResourceReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceReadingProfile.Marshal(b, m, deterministic)
}
func (m *ResourceReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceReadingProfile.Merge(m, src)
}
func (m *ResourceReadingProfile) XXX_Size() int {
	return xxx_messageInfo_ResourceReadingProfile.Size(m)
}
func (m *ResourceReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceReadingProfile proto.InternalMessageInfo

func (m *ResourceReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *ResourceReadingProfile) GetConductingEquipment() *commonmodule.ConductingEquipment {
	if m != nil {
		return m.ConductingEquipment
	}
	return nil
}

func (m *ResourceReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *ResourceReadingProfile) GetResourceReading() *ResourceReading {
	if m != nil {
		return m.ResourceReading
	}
	return nil
}

// Current status information relevant to an entity.
type ResourceStatus struct {
	// UML inherited base object
	StatusValue *commonmodule.StatusValue `protobuf:"bytes,1,opt,name=statusValue,proto3" json:"statusValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	AnalogStatusGGIO []*commonmodule.AnalogStatusGGIO `protobuf:"bytes,2,rep,name=analogStatusGGIO,proto3" json:"analogStatusGGIO,omitempty"`
	// MISSING DOCUMENTATION!!!
	BooleanStatusGGIO []*commonmodule.BooleanStatusGGIO `protobuf:"bytes,3,rep,name=booleanStatusGGIO,proto3" json:"booleanStatusGGIO,omitempty"`
	// MISSING DOCUMENTATION!!!
	IntegerStatusGGIO []*commonmodule.IntegerStatusGGIO `protobuf:"bytes,4,rep,name=integerStatusGGIO,proto3" json:"integerStatusGGIO,omitempty"`
	// MISSING DOCUMENTATION!!!
	StringStatusGGIO     []*commonmodule.StringStatusGGIO `protobuf:"bytes,5,rep,name=stringStatusGGIO,proto3" json:"stringStatusGGIO,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ResourceStatus) Reset()         { *m = ResourceStatus{} }
func (m *ResourceStatus) String() string { return proto.CompactTextString(m) }
func (*ResourceStatus) ProtoMessage()    {}
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfd19c4ccf8ab43, []int{2}
}

func (m *ResourceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatus.Unmarshal(m, b)
}
func (m *ResourceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatus.Marshal(b, m, deterministic)
}
func (m *ResourceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatus.Merge(m, src)
}
func (m *ResourceStatus) XXX_Size() int {
	return xxx_messageInfo_ResourceStatus.Size(m)
}
func (m *ResourceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatus proto.InternalMessageInfo

func (m *ResourceStatus) GetStatusValue() *commonmodule.StatusValue {
	if m != nil {
		return m.StatusValue
	}
	return nil
}

func (m *ResourceStatus) GetAnalogStatusGGIO() []*commonmodule.AnalogStatusGGIO {
	if m != nil {
		return m.AnalogStatusGGIO
	}
	return nil
}

func (m *ResourceStatus) GetBooleanStatusGGIO() []*commonmodule.BooleanStatusGGIO {
	if m != nil {
		return m.BooleanStatusGGIO
	}
	return nil
}

func (m *ResourceStatus) GetIntegerStatusGGIO() []*commonmodule.IntegerStatusGGIO {
	if m != nil {
		return m.IntegerStatusGGIO
	}
	return nil
}

func (m *ResourceStatus) GetStringStatusGGIO() []*commonmodule.StringStatusGGIO {
	if m != nil {
		return m.StringStatusGGIO
	}
	return nil
}

// Resource status module
type ResourceStatusProfile struct {
	// UML inherited base object
	StatusMessageInfo *commonmodule.StatusMessageInfo `protobuf:"bytes,1,opt,name=statusMessageInfo,proto3" json:"statusMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	ConductingEquipment *commonmodule.ConductingEquipment `protobuf:"bytes,2,opt,name=conductingEquipment,proto3" json:"conductingEquipment,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,3,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	ResourceStatus       *ResourceStatus `protobuf:"bytes,4,opt,name=resourceStatus,proto3" json:"resourceStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResourceStatusProfile) Reset()         { *m = ResourceStatusProfile{} }
func (m *ResourceStatusProfile) String() string { return proto.CompactTextString(m) }
func (*ResourceStatusProfile) ProtoMessage()    {}
func (*ResourceStatusProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cfd19c4ccf8ab43, []int{3}
}

func (m *ResourceStatusProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatusProfile.Unmarshal(m, b)
}
func (m *ResourceStatusProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatusProfile.Marshal(b, m, deterministic)
}
func (m *ResourceStatusProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatusProfile.Merge(m, src)
}
func (m *ResourceStatusProfile) XXX_Size() int {
	return xxx_messageInfo_ResourceStatusProfile.Size(m)
}
func (m *ResourceStatusProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatusProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatusProfile proto.InternalMessageInfo

func (m *ResourceStatusProfile) GetStatusMessageInfo() *commonmodule.StatusMessageInfo {
	if m != nil {
		return m.StatusMessageInfo
	}
	return nil
}

func (m *ResourceStatusProfile) GetConductingEquipment() *commonmodule.ConductingEquipment {
	if m != nil {
		return m.ConductingEquipment
	}
	return nil
}

func (m *ResourceStatusProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *ResourceStatusProfile) GetResourceStatus() *ResourceStatus {
	if m != nil {
		return m.ResourceStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceReading)(nil), "resourcemodule.ResourceReading")
	proto.RegisterType((*ResourceReadingProfile)(nil), "resourcemodule.ResourceReadingProfile")
	proto.RegisterType((*ResourceStatus)(nil), "resourcemodule.ResourceStatus")
	proto.RegisterType((*ResourceStatusProfile)(nil), "resourcemodule.ResourceStatusProfile")
}

func init() {
	proto.RegisterFile("resourcemodule/resourcemodule.proto", fileDescriptor_9cfd19c4ccf8ab43)
}

var fileDescriptor_9cfd19c4ccf8ab43 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x1c, 0xc5, 0xb1, 0x13, 0x10, 0xbd, 0x48, 0x2d, 0x39, 0x44, 0x31, 0x1d, 0x9a, 0x10, 0x96, 0x2e,
	0x89, 0x51, 0x11, 0x0b, 0x4c, 0x35, 0x54, 0x55, 0x86, 0x80, 0x75, 0x4e, 0xab, 0x0a, 0x89, 0xe1,
	0x9c, 0x5c, 0x8c, 0x25, 0xfb, 0xce, 0xf8, 0xec, 0x9d, 0x09, 0x18, 0xfb, 0x15, 0x58, 0xd9, 0xb3,
	0xb3, 0xb3, 0xb1, 0xf1, 0x39, 0xf8, 0x02, 0xc8, 0xf6, 0xb9, 0xb9, 0x3b, 0xbb, 0x94, 0xb1, 0x9b,
	0xed, 0x7b, 0xef, 0x77, 0xfe, 0xbf, 0x7b, 0x3a, 0xf0, 0x24, 0x25, 0x9c, 0xe5, 0xe9, 0x82, 0xc4,
	0x6c, 0x99, 0x47, 0xc4, 0x56, 0x5f, 0x27, 0x49, 0xca, 0x32, 0x06, 0xb7, 0xd5, 0xaf, 0x7b, 0x5b,
	0x79, 0x1c, 0x55, 0x4b, 0x7b, 0x83, 0x05, 0x8b, 0x63, 0x46, 0x85, 0x5b, 0x7e, 0xa9, 0x04, 0xa3,
	0x9f, 0x26, 0xd8, 0x41, 0xc2, 0x8e, 0x08, 0x5e, 0x86, 0x34, 0x80, 0x9f, 0x0d, 0x30, 0x5a, 0x30,
	0xba, 0xcc, 0x17, 0x59, 0x48, 0x83, 0xe3, 0x8f, 0x79, 0x98, 0xc4, 0x84, 0x66, 0x73, 0x92, 0xc6,
	0x21, 0xc5, 0x91, 0x90, 0x59, 0xc6, 0xd0, 0x38, 0xe8, 0x1d, 0x3e, 0x9d, 0x28, 0xd4, 0x57, 0xd7,
	0xfa, 0x9c, 0xee, 0xa7, 0xb5, 0x65, 0xa0, 0xff, 0xd8, 0x01, 0x3e, 0x07, 0x5b, 0xc9, 0x07, 0xcc,
	0xc9, 0x6c, 0x36, 0x7f, 0x63, 0x99, 0xe5, 0x76, 0x0f, 0xd5, 0xed, 0xdc, 0x7a, 0x19, 0x6d, 0x94,
	0xf0, 0x25, 0xe8, 0xa5, 0x15, 0x61, 0x36, 0x9b, 0x23, 0xab, 0x53, 0x1a, 0x1f, 0xa9, 0x46, 0xb4,
	0x11, 0x20, 0x59, 0xad, 0x98, 0xcf, 0x4f, 0xad, 0xee, 0x3f, 0xcd, 0xe7, 0xa7, 0x48, 0x56, 0x8f,
	0x7e, 0x9b, 0x60, 0x57, 0x4b, 0xd3, 0x4d, 0xd9, 0x2a, 0x8c, 0x08, 0x3c, 0x03, 0xb0, 0x56, 0x12,
	0xce, 0x71, 0x40, 0xa6, 0x74, 0xc5, 0x44, 0x86, 0xc3, 0x76, 0xfc, 0x46, 0x27, 0x32, 0x6b, 0x21,
	0xc0, 0xf7, 0xe0, 0x7e, 0x4b, 0x92, 0x22, 0xad, 0xc7, 0xd7, 0x1e, 0x8e, 0x73, 0xf7, 0xeb, 0xda,
	0x32, 0x2e, 0x0a, 0x7a, 0x1b, 0x07, 0x8e, 0x41, 0x27, 0x24, 0x4b, 0x91, 0x61, 0x5f, 0xc5, 0x4d,
	0x8f, 0x5f, 0x4b, 0xf6, 0x42, 0x07, 0x3d, 0xb0, 0x93, 0xaa, 0xf3, 0x8b, 0x04, 0x07, 0x13, 0xad,
	0xba, 0x5a, 0x4c, 0x12, 0x48, 0x27, 0xbc, 0xe8, 0xfe, 0xf8, 0x63, 0x19, 0xa3, 0x6f, 0x1d, 0xb0,
	0x5d, 0x9b, 0xbc, 0x0c, 0x67, 0x39, 0x87, 0x47, 0xa0, 0xc7, 0xcb, 0xa7, 0x33, 0x1c, 0xe5, 0x44,
	0x84, 0xa9, 0x9d, 0x95, 0xb7, 0x11, 0x88, 0x14, 0x65, 0x0f, 0x74, 0xc1, 0x3d, 0x4c, 0x71, 0xc4,
	0x82, 0x4a, 0x77, 0x72, 0x32, 0x7d, 0x6b, 0x99, 0xc3, 0xce, 0x41, 0xef, 0x70, 0x5f, 0xe5, 0x1c,
	0x69, 0x2a, 0xa7, 0x7b, 0xb1, 0xb6, 0x6e, 0xa1, 0x86, 0x1b, 0x7a, 0xa0, 0xef, 0x33, 0x16, 0x11,
	0x4c, 0x25, 0x64, 0xa7, 0x44, 0x0e, 0x54, 0xa4, 0xa3, 0xcb, 0x04, 0xb3, 0xe9, 0x2f, 0xa0, 0x21,
	0xcd, 0x48, 0x40, 0x52, 0x09, 0xda, 0x6d, 0x83, 0x4e, 0x75, 0x59, 0x0d, 0x6d, 0xf8, 0x8b, 0xd9,
	0x79, 0x96, 0x86, 0x54, 0x9e, 0xfd, 0x76, 0xdb, 0xec, 0x9e, 0xa6, 0xaa, 0x67, 0xd7, 0xdd, 0xa3,
	0x5f, 0x26, 0x78, 0xa0, 0x9e, 0x51, 0x5d, 0x7f, 0x0f, 0xf4, 0xab, 0xd8, 0x9b, 0xed, 0x1f, 0xb4,
	0x1d, 0x58, 0xb3, 0xfc, 0x4d, 0xff, 0x0d, 0xeb, 0xbe, 0x0b, 0x2e, 0x2f, 0xe2, 0x6a, 0x06, 0x51,
	0xfd, 0xfd, 0xab, 0xaa, 0x5f, 0xa9, 0x24, 0x8c, 0xe6, 0xaf, 0x8a, 0xef, 0x7c, 0x31, 0xc0, 0x2e,
	0x4b, 0x08, 0x5d, 0xc5, 0xbe, 0x46, 0x72, 0x8d, 0x77, 0x28, 0x08, 0xb3, 0x08, 0xfb, 0xc5, 0xcf,
	0xd9, 0x42, 0x64, 0x27, 0xbc, 0x78, 0xe6, 0x76, 0x79, 0xc3, 0xfb, 0xf9, 0xca, 0x0e, 0xd8, 0x58,
	0xac, 0x8d, 0x59, 0xc2, 0xc7, 0x97, 0xdf, 0x6b, 0x83, 0x4a, 0xfd, 0x6e, 0x5e, 0xb1, 0x9d, 0x7f,
	0xa7, 0x74, 0x3e, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x15, 0x59, 0xab, 0x35, 0x96, 0x06, 0x00,
	0x00,
}
