// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metermodule/metermodule.proto

package metermodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource reading value
type MeterReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,2,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,3,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,4,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MeterReading) Reset()         { *m = MeterReading{} }
func (m *MeterReading) String() string { return proto.CompactTextString(m) }
func (*MeterReading) ProtoMessage()    {}
func (*MeterReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a3208d1cde56c6c, []int{0}
}

func (m *MeterReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeterReading.Unmarshal(m, b)
}
func (m *MeterReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeterReading.Marshal(b, m, deterministic)
}
func (m *MeterReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeterReading.Merge(m, src)
}
func (m *MeterReading) XXX_Size() int {
	return xxx_messageInfo_MeterReading.Size(m)
}
func (m *MeterReading) XXX_DiscardUnknown() {
	xxx_messageInfo_MeterReading.DiscardUnknown(m)
}

var xxx_messageInfo_MeterReading proto.InternalMessageInfo

func (m *MeterReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *MeterReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *MeterReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *MeterReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Resource reading profile
type MeterReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied *commonmodule.IED `protobuf:"bytes,2,opt,name=ied,proto3" json:"ied,omitempty"`
	// MISSING DOCUMENTATION!!!
	Meter *commonmodule.Meter `protobuf:"bytes,3,opt,name=meter,proto3" json:"meter,omitempty"`
	// MISSING DOCUMENTATION!!!
	MeterReading         *MeterReading `protobuf:"bytes,4,opt,name=meterReading,proto3" json:"meterReading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MeterReadingProfile) Reset()         { *m = MeterReadingProfile{} }
func (m *MeterReadingProfile) String() string { return proto.CompactTextString(m) }
func (*MeterReadingProfile) ProtoMessage()    {}
func (*MeterReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a3208d1cde56c6c, []int{1}
}

func (m *MeterReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeterReadingProfile.Unmarshal(m, b)
}
func (m *MeterReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeterReadingProfile.Marshal(b, m, deterministic)
}
func (m *MeterReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeterReadingProfile.Merge(m, src)
}
func (m *MeterReadingProfile) XXX_Size() int {
	return xxx_messageInfo_MeterReadingProfile.Size(m)
}
func (m *MeterReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_MeterReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_MeterReadingProfile proto.InternalMessageInfo

func (m *MeterReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *MeterReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func (m *MeterReadingProfile) GetMeter() *commonmodule.Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *MeterReadingProfile) GetMeterReading() *MeterReading {
	if m != nil {
		return m.MeterReading
	}
	return nil
}

func init() {
	proto.RegisterType((*MeterReading)(nil), "metermodule.MeterReading")
	proto.RegisterType((*MeterReadingProfile)(nil), "metermodule.MeterReadingProfile")
}

func init() { proto.RegisterFile("metermodule/metermodule.proto", fileDescriptor_3a3208d1cde56c6c) }

var fileDescriptor_3a3208d1cde56c6c = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x4e, 0xeb, 0x30,
	0x1c, 0x85, 0x95, 0xb4, 0xf7, 0x8a, 0xba, 0x5d, 0x70, 0x07, 0x4c, 0x25, 0x44, 0xd5, 0x89, 0x25,
	0x0d, 0xa2, 0x62, 0x81, 0xad, 0x50, 0xa1, 0x0e, 0x81, 0xca, 0x6a, 0x51, 0xc5, 0x96, 0x34, 0x4e,
	0xb0, 0x14, 0xdb, 0x21, 0x7f, 0x56, 0xc4, 0x84, 0x18, 0x79, 0x04, 0x66, 0xf6, 0xee, 0x8c, 0xbc,
	0x0f, 0x2f, 0x80, 0x92, 0xb8, 0xad, 0x2d, 0x55, 0xc0, 0x96, 0xd8, 0xdf, 0x77, 0x7e, 0xf6, 0x91,
	0xc1, 0x01, 0x23, 0x19, 0x49, 0x98, 0xf0, 0xf3, 0x88, 0xd8, 0xca, 0x77, 0x3f, 0x4e, 0x44, 0x26,
	0x60, 0x53, 0x59, 0xea, 0x34, 0x72, 0x16, 0x55, 0xeb, 0x9d, 0xc3, 0x85, 0x60, 0x4c, 0x70, 0xe9,
	0xa9, 0x3f, 0x15, 0xd0, 0xfb, 0x34, 0x41, 0xcb, 0x29, 0x5c, 0x4c, 0x5c, 0x9f, 0xf2, 0x10, 0x3e,
	0x1b, 0xa0, 0xb7, 0x10, 0xdc, 0xcf, 0x17, 0x19, 0xe5, 0xe1, 0xe8, 0x21, 0xa7, 0x31, 0x23, 0x3c,
	0x9b, 0x92, 0x84, 0x51, 0xee, 0x46, 0x12, 0x43, 0x46, 0xd7, 0x38, 0x6a, 0x9e, 0x1c, 0xf7, 0xb5,
	0xc8, 0x8b, 0x5f, 0xbd, 0x61, 0xfd, 0x69, 0x89, 0x0c, 0xfc, 0x87, 0x09, 0xf0, 0x14, 0x34, 0xe2,
	0x7b, 0x37, 0x25, 0x8e, 0x33, 0xbd, 0x46, 0x66, 0x39, 0x6e, 0x4f, 0x1f, 0x37, 0x59, 0x6d, 0xe3,
	0x0d, 0x09, 0xcf, 0x41, 0x33, 0xa9, 0x12, 0x1c, 0x67, 0x8a, 0x51, 0xad, 0x14, 0xf7, 0x75, 0x11,
	0x6f, 0x00, 0xac, 0xd2, 0x9a, 0x3c, 0x9f, 0xa1, 0xfa, 0x8f, 0xf2, 0x7c, 0x86, 0x55, 0xba, 0xf7,
	0x66, 0x82, 0xb6, 0x5a, 0xe5, 0x24, 0x11, 0x01, 0x8d, 0x08, 0xbc, 0x05, 0x70, 0x85, 0x91, 0x34,
	0x75, 0x43, 0x32, 0xe6, 0x81, 0x90, 0x05, 0x76, 0xb7, 0x67, 0x6f, 0x38, 0x59, 0xd8, 0x96, 0x04,
	0x68, 0x81, 0x1a, 0x25, 0xbe, 0xac, 0x66, 0x57, 0x0f, 0x1a, 0x8f, 0x2e, 0x87, 0x3b, 0x2f, 0x4b,
	0x64, 0xbc, 0x16, 0x76, 0xc1, 0xc1, 0x01, 0xf8, 0x57, 0x3e, 0x12, 0x59, 0x49, 0x5b, 0x17, 0xca,
	0x83, 0x2b, 0x4a, 0xc5, 0xc2, 0x2b, 0xd0, 0x62, 0xca, 0x95, 0xd6, 0x8d, 0xa8, 0x2f, 0x50, 0xbd,
	0xb3, 0x92, 0xa0, 0x89, 0x67, 0xf5, 0x8f, 0x2f, 0x64, 0x0c, 0x1f, 0x41, 0x5b, 0xc4, 0x84, 0x07,
	0xcc, 0x53, 0x13, 0x26, 0xc6, 0xdd, 0x4d, 0x48, 0xb3, 0xc8, 0xf5, 0x8a, 0x33, 0xd9, 0x92, 0xb0,
	0xe3, 0xb4, 0xf8, 0x4e, 0xed, 0xf2, 0xa1, 0x7a, 0x79, 0x60, 0x87, 0xc2, 0x92, 0x7b, 0x96, 0x88,
	0x53, 0x6b, 0xbd, 0xbe, 0x12, 0x94, 0xc8, 0x77, 0x73, 0xdb, 0x20, 0xef, 0x7f, 0xe9, 0x0c, 0xbe,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x61, 0x56, 0x32, 0xc8, 0x4e, 0x03, 0x00, 0x00,
}
