// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generationmodule/generationmodule.proto

package generationmodule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb"
	commonmodule "gitlab.com/openfmb/psm/ops/protobuf/go-openfmb-ops-protobuf/openfmb/commonmodule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Point definition (Point)
type GenerationPoint struct {
	// Black start enable
	BlackStartEnabled *commonmodule.ControlDPC `protobuf:"bytes,1,opt,name=blackStartEnabled,proto3" json:"blackStartEnabled,omitempty"`
	// Enable frequency set point
	FrequencySetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=frequencySetPointEnabled,proto3" json:"frequencySetPointEnabled,omitempty"`
	// Black start enable
	PctHzDroop *wrappers.FloatValue `protobuf:"bytes,3,opt,name=pctHzDroop,proto3" json:"pctHzDroop,omitempty"`
	// Black start enable
	PctVDroop *wrappers.FloatValue `protobuf:"bytes,4,opt,name=pctVDroop,proto3" json:"pctVDroop,omitempty"`
	// Ramp rates
	RampRates *commonmodule.RampRate `protobuf:"bytes,5,opt,name=rampRates,proto3" json:"rampRates,omitempty"`
	// Enable reactive power set point
	ReactivePwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,6,opt,name=reactivePwrSetPointEnabled,proto3" json:"reactivePwrSetPointEnabled,omitempty"`
	// Enable joint real power set point
	RealPwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,7,opt,name=realPwrSetPointEnabled,proto3" json:"realPwrSetPointEnabled,omitempty"`
	// Reset device
	Reset_ *commonmodule.ControlDPC `protobuf:"bytes,8,opt,name=reset,proto3" json:"reset,omitempty"`
	// ESS state
	State *commonmodule.Optional_StateKind `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	// Synchronize back to grid
	SyncBackToGrid *commonmodule.ControlDPC `protobuf:"bytes,10,opt,name=syncBackToGrid,proto3" json:"syncBackToGrid,omitempty"`
	// Transition to island on grid loss enable
	TransToIslndOnGridLossEnabled *commonmodule.ControlDPC `protobuf:"bytes,11,opt,name=transToIslndOnGridLossEnabled,proto3" json:"transToIslndOnGridLossEnabled,omitempty"`
	// Enable voltage set point
	VoltageSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,12,opt,name=voltageSetPointEnabled,proto3" json:"voltageSetPointEnabled,omitempty"`
	// Start time
	StartTime            *commonmodule.ControlTimestamp `protobuf:"bytes,13,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GenerationPoint) Reset()         { *m = GenerationPoint{} }
func (m *GenerationPoint) String() string { return proto.CompactTextString(m) }
func (*GenerationPoint) ProtoMessage()    {}
func (*GenerationPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{0}
}

func (m *GenerationPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationPoint.Unmarshal(m, b)
}
func (m *GenerationPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationPoint.Marshal(b, m, deterministic)
}
func (m *GenerationPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationPoint.Merge(m, src)
}
func (m *GenerationPoint) XXX_Size() int {
	return xxx_messageInfo_GenerationPoint.Size(m)
}
func (m *GenerationPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationPoint.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationPoint proto.InternalMessageInfo

func (m *GenerationPoint) GetBlackStartEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.BlackStartEnabled
	}
	return nil
}

func (m *GenerationPoint) GetFrequencySetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.FrequencySetPointEnabled
	}
	return nil
}

func (m *GenerationPoint) GetPctHzDroop() *wrappers.FloatValue {
	if m != nil {
		return m.PctHzDroop
	}
	return nil
}

func (m *GenerationPoint) GetPctVDroop() *wrappers.FloatValue {
	if m != nil {
		return m.PctVDroop
	}
	return nil
}

func (m *GenerationPoint) GetRampRates() *commonmodule.RampRate {
	if m != nil {
		return m.RampRates
	}
	return nil
}

func (m *GenerationPoint) GetReactivePwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.ReactivePwrSetPointEnabled
	}
	return nil
}

func (m *GenerationPoint) GetRealPwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.RealPwrSetPointEnabled
	}
	return nil
}

func (m *GenerationPoint) GetReset_() *commonmodule.ControlDPC {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func (m *GenerationPoint) GetState() *commonmodule.Optional_StateKind {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GenerationPoint) GetSyncBackToGrid() *commonmodule.ControlDPC {
	if m != nil {
		return m.SyncBackToGrid
	}
	return nil
}

func (m *GenerationPoint) GetTransToIslndOnGridLossEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.TransToIslndOnGridLossEnabled
	}
	return nil
}

func (m *GenerationPoint) GetVoltageSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.VoltageSetPointEnabled
	}
	return nil
}

func (m *GenerationPoint) GetStartTime() *commonmodule.ControlTimestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

// Curve shape setting (FC=SP) (CSG_SP)
type GenerationCSG struct {
	// The array with the points specifying a curve shape.
	CrvPts               []*GenerationPoint `protobuf:"bytes,1,rep,name=crvPts,proto3" json:"crvPts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GenerationCSG) Reset()         { *m = GenerationCSG{} }
func (m *GenerationCSG) String() string { return proto.CompactTextString(m) }
func (*GenerationCSG) ProtoMessage()    {}
func (*GenerationCSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{1}
}

func (m *GenerationCSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationCSG.Unmarshal(m, b)
}
func (m *GenerationCSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationCSG.Marshal(b, m, deterministic)
}
func (m *GenerationCSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationCSG.Merge(m, src)
}
func (m *GenerationCSG) XXX_Size() int {
	return xxx_messageInfo_GenerationCSG.Size(m)
}
func (m *GenerationCSG) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationCSG.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationCSG proto.InternalMessageInfo

func (m *GenerationCSG) GetCrvPts() []*GenerationPoint {
	if m != nil {
		return m.CrvPts
	}
	return nil
}

// OpenFMB specialization for control schedule using:  LN: Schedule   Name: FSCH
type GenerationControlScheduleFSCH struct {
	// Discrete value in GenerationCSG type
	ValDCSG              *GenerationCSG `protobuf:"bytes,1,opt,name=ValDCSG,proto3" json:"ValDCSG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GenerationControlScheduleFSCH) Reset()         { *m = GenerationControlScheduleFSCH{} }
func (m *GenerationControlScheduleFSCH) String() string { return proto.CompactTextString(m) }
func (*GenerationControlScheduleFSCH) ProtoMessage()    {}
func (*GenerationControlScheduleFSCH) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{2}
}

func (m *GenerationControlScheduleFSCH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationControlScheduleFSCH.Unmarshal(m, b)
}
func (m *GenerationControlScheduleFSCH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationControlScheduleFSCH.Marshal(b, m, deterministic)
}
func (m *GenerationControlScheduleFSCH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationControlScheduleFSCH.Merge(m, src)
}
func (m *GenerationControlScheduleFSCH) XXX_Size() int {
	return xxx_messageInfo_GenerationControlScheduleFSCH.Size(m)
}
func (m *GenerationControlScheduleFSCH) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationControlScheduleFSCH.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationControlScheduleFSCH proto.InternalMessageInfo

func (m *GenerationControlScheduleFSCH) GetValDCSG() *GenerationCSG {
	if m != nil {
		return m.ValDCSG
	}
	return nil
}

// LN: Schedule controller   Name: FSCC
type GenerationControlFSCC struct {
	// UML inherited base object
	ControlFSCC *commonmodule.ControlFSCC `protobuf:"bytes,1,opt,name=controlFSCC,proto3" json:"controlFSCC,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationControlScheduleFSCH *GenerationControlScheduleFSCH `protobuf:"bytes,2,opt,name=GenerationControlScheduleFSCH,proto3" json:"GenerationControlScheduleFSCH,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                       `json:"-"`
	XXX_unrecognized              []byte                         `json:"-"`
	XXX_sizecache                 int32                          `json:"-"`
}

func (m *GenerationControlFSCC) Reset()         { *m = GenerationControlFSCC{} }
func (m *GenerationControlFSCC) String() string { return proto.CompactTextString(m) }
func (*GenerationControlFSCC) ProtoMessage()    {}
func (*GenerationControlFSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{3}
}

func (m *GenerationControlFSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationControlFSCC.Unmarshal(m, b)
}
func (m *GenerationControlFSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationControlFSCC.Marshal(b, m, deterministic)
}
func (m *GenerationControlFSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationControlFSCC.Merge(m, src)
}
func (m *GenerationControlFSCC) XXX_Size() int {
	return xxx_messageInfo_GenerationControlFSCC.Size(m)
}
func (m *GenerationControlFSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationControlFSCC.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationControlFSCC proto.InternalMessageInfo

func (m *GenerationControlFSCC) GetControlFSCC() *commonmodule.ControlFSCC {
	if m != nil {
		return m.ControlFSCC
	}
	return nil
}

func (m *GenerationControlFSCC) GetGenerationControlScheduleFSCH() *GenerationControlScheduleFSCH {
	if m != nil {
		return m.GenerationControlScheduleFSCH
	}
	return nil
}

// Generation control
type GenerationControl struct {
	// UML inherited base object
	ControlValue *commonmodule.ControlValue `protobuf:"bytes,1,opt,name=controlValue,proto3" json:"controlValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	Check *commonmodule.CheckConditions `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationControlFSCC *GenerationControlFSCC `protobuf:"bytes,3,opt,name=generationControlFSCC,proto3" json:"generationControlFSCC,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *GenerationControl) Reset()         { *m = GenerationControl{} }
func (m *GenerationControl) String() string { return proto.CompactTextString(m) }
func (*GenerationControl) ProtoMessage()    {}
func (*GenerationControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{4}
}

func (m *GenerationControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationControl.Unmarshal(m, b)
}
func (m *GenerationControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationControl.Marshal(b, m, deterministic)
}
func (m *GenerationControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationControl.Merge(m, src)
}
func (m *GenerationControl) XXX_Size() int {
	return xxx_messageInfo_GenerationControl.Size(m)
}
func (m *GenerationControl) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationControl.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationControl proto.InternalMessageInfo

func (m *GenerationControl) GetControlValue() *commonmodule.ControlValue {
	if m != nil {
		return m.ControlValue
	}
	return nil
}

func (m *GenerationControl) GetCheck() *commonmodule.CheckConditions {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *GenerationControl) GetGenerationControlFSCC() *GenerationControlFSCC {
	if m != nil {
		return m.GenerationControlFSCC
	}
	return nil
}

// A single or set of synchronous machines for converting mechanical power into alternating-current
// power. For example, individual machines within a set may be defined for scheduling purposes while a
// single control signal is derived for the set. In this case there would be a GeneratingUnit for each
// member of the set and an additional GeneratingUnit corresponding to the set.
type GeneratingUnit struct {
	// UML inherited base object
	ConductingEquipment *commonmodule.ConductingEquipment `protobuf:"bytes,1,opt,name=conductingEquipment,proto3" json:"conductingEquipment,omitempty"`
	// This is the maximum operating active power limit the dispatcher can enter for this unit.
	MaxOperatingP        *commonmodule.ActivePower `protobuf:"bytes,2,opt,name=maxOperatingP,proto3" json:"maxOperatingP,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GeneratingUnit) Reset()         { *m = GeneratingUnit{} }
func (m *GeneratingUnit) String() string { return proto.CompactTextString(m) }
func (*GeneratingUnit) ProtoMessage()    {}
func (*GeneratingUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{5}
}

func (m *GeneratingUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratingUnit.Unmarshal(m, b)
}
func (m *GeneratingUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratingUnit.Marshal(b, m, deterministic)
}
func (m *GeneratingUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratingUnit.Merge(m, src)
}
func (m *GeneratingUnit) XXX_Size() int {
	return xxx_messageInfo_GeneratingUnit.Size(m)
}
func (m *GeneratingUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratingUnit.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratingUnit proto.InternalMessageInfo

func (m *GeneratingUnit) GetConductingEquipment() *commonmodule.ConductingEquipment {
	if m != nil {
		return m.ConductingEquipment
	}
	return nil
}

func (m *GeneratingUnit) GetMaxOperatingP() *commonmodule.ActivePower {
	if m != nil {
		return m.MaxOperatingP
	}
	return nil
}

// Generation control profile
type GenerationControlProfile struct {
	// UML inherited base object
	ControlMessageInfo *commonmodule.ControlMessageInfo `protobuf:"bytes,1,opt,name=controlMessageInfo,proto3" json:"controlMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	GeneratingUnit *GeneratingUnit `protobuf:"bytes,2,opt,name=generatingUnit,proto3" json:"generatingUnit,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationControl *GenerationControl `protobuf:"bytes,3,opt,name=generationControl,proto3" json:"generationControl,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerationControlProfile) Reset()         { *m = GenerationControlProfile{} }
func (m *GenerationControlProfile) String() string { return proto.CompactTextString(m) }
func (*GenerationControlProfile) ProtoMessage()    {}
func (*GenerationControlProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{6}
}

func (m *GenerationControlProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationControlProfile.Unmarshal(m, b)
}
func (m *GenerationControlProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationControlProfile.Marshal(b, m, deterministic)
}
func (m *GenerationControlProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationControlProfile.Merge(m, src)
}
func (m *GenerationControlProfile) XXX_Size() int {
	return xxx_messageInfo_GenerationControlProfile.Size(m)
}
func (m *GenerationControlProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationControlProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationControlProfile proto.InternalMessageInfo

func (m *GenerationControlProfile) GetControlMessageInfo() *commonmodule.ControlMessageInfo {
	if m != nil {
		return m.ControlMessageInfo
	}
	return nil
}

func (m *GenerationControlProfile) GetGeneratingUnit() *GeneratingUnit {
	if m != nil {
		return m.GeneratingUnit
	}
	return nil
}

func (m *GenerationControlProfile) GetGenerationControl() *GenerationControl {
	if m != nil {
		return m.GenerationControl
	}
	return nil
}

func (m *GenerationControlProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// Generation reading value
type GenerationReading struct {
	// UML inherited base object
	ConductingEquipmentTerminalReading *commonmodule.ConductingEquipmentTerminalReading `protobuf:"bytes,1,opt,name=conductingEquipmentTerminalReading,proto3" json:"conductingEquipmentTerminalReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	PhaseMMTN *commonmodule.PhaseMMTN `protobuf:"bytes,2,opt,name=phaseMMTN,proto3" json:"phaseMMTN,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMTR *commonmodule.ReadingMMTR `protobuf:"bytes,3,opt,name=readingMMTR,proto3" json:"readingMMTR,omitempty"`
	// MISSING DOCUMENTATION!!!
	ReadingMMXU          *commonmodule.ReadingMMXU `protobuf:"bytes,4,opt,name=readingMMXU,proto3" json:"readingMMXU,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GenerationReading) Reset()         { *m = GenerationReading{} }
func (m *GenerationReading) String() string { return proto.CompactTextString(m) }
func (*GenerationReading) ProtoMessage()    {}
func (*GenerationReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{7}
}

func (m *GenerationReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationReading.Unmarshal(m, b)
}
func (m *GenerationReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationReading.Marshal(b, m, deterministic)
}
func (m *GenerationReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationReading.Merge(m, src)
}
func (m *GenerationReading) XXX_Size() int {
	return xxx_messageInfo_GenerationReading.Size(m)
}
func (m *GenerationReading) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationReading.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationReading proto.InternalMessageInfo

func (m *GenerationReading) GetConductingEquipmentTerminalReading() *commonmodule.ConductingEquipmentTerminalReading {
	if m != nil {
		return m.ConductingEquipmentTerminalReading
	}
	return nil
}

func (m *GenerationReading) GetPhaseMMTN() *commonmodule.PhaseMMTN {
	if m != nil {
		return m.PhaseMMTN
	}
	return nil
}

func (m *GenerationReading) GetReadingMMTR() *commonmodule.ReadingMMTR {
	if m != nil {
		return m.ReadingMMTR
	}
	return nil
}

func (m *GenerationReading) GetReadingMMXU() *commonmodule.ReadingMMXU {
	if m != nil {
		return m.ReadingMMXU
	}
	return nil
}

// Generation reading profile
type GenerationReadingProfile struct {
	// UML inherited base object
	ReadingMessageInfo *commonmodule.ReadingMessageInfo `protobuf:"bytes,1,opt,name=readingMessageInfo,proto3" json:"readingMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	GeneratingUnit *GeneratingUnit `protobuf:"bytes,2,opt,name=generatingUnit,proto3" json:"generatingUnit,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationReading *GenerationReading `protobuf:"bytes,3,opt,name=generationReading,proto3" json:"generationReading,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerationReadingProfile) Reset()         { *m = GenerationReadingProfile{} }
func (m *GenerationReadingProfile) String() string { return proto.CompactTextString(m) }
func (*GenerationReadingProfile) ProtoMessage()    {}
func (*GenerationReadingProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{8}
}

func (m *GenerationReadingProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationReadingProfile.Unmarshal(m, b)
}
func (m *GenerationReadingProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationReadingProfile.Marshal(b, m, deterministic)
}
func (m *GenerationReadingProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationReadingProfile.Merge(m, src)
}
func (m *GenerationReadingProfile) XXX_Size() int {
	return xxx_messageInfo_GenerationReadingProfile.Size(m)
}
func (m *GenerationReadingProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationReadingProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationReadingProfile proto.InternalMessageInfo

func (m *GenerationReadingProfile) GetReadingMessageInfo() *commonmodule.ReadingMessageInfo {
	if m != nil {
		return m.ReadingMessageInfo
	}
	return nil
}

func (m *GenerationReadingProfile) GetGeneratingUnit() *GeneratingUnit {
	if m != nil {
		return m.GeneratingUnit
	}
	return nil
}

func (m *GenerationReadingProfile) GetGenerationReading() *GenerationReading {
	if m != nil {
		return m.GenerationReading
	}
	return nil
}

func (m *GenerationReadingProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// Point definition (Point)
type GenerationPointStatus struct {
	// Black start enable
	BlackStartEnabled *commonmodule.ControlDPC `protobuf:"bytes,1,opt,name=blackStartEnabled,proto3" json:"blackStartEnabled,omitempty"`
	// Enable frequency set point
	FrequencySetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,2,opt,name=frequencySetPointEnabled,proto3" json:"frequencySetPointEnabled,omitempty"`
	// Black start enable
	PctHzDroop *wrappers.FloatValue `protobuf:"bytes,3,opt,name=pctHzDroop,proto3" json:"pctHzDroop,omitempty"`
	// Black start enable
	PctVDroop *wrappers.FloatValue `protobuf:"bytes,4,opt,name=pctVDroop,proto3" json:"pctVDroop,omitempty"`
	// Ramp rates
	RampRates *commonmodule.RampRate `protobuf:"bytes,5,opt,name=rampRates,proto3" json:"rampRates,omitempty"`
	// Enable reactive power set point
	ReactivePwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,6,opt,name=reactivePwrSetPointEnabled,proto3" json:"reactivePwrSetPointEnabled,omitempty"`
	// Enable real power set point
	RealPwrSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,7,opt,name=realPwrSetPointEnabled,proto3" json:"realPwrSetPointEnabled,omitempty"`
	// ESS state
	State *commonmodule.Optional_StateKind `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	// Synchronize back to grid
	SyncBackToGrid *commonmodule.ControlDPC `protobuf:"bytes,9,opt,name=syncBackToGrid,proto3" json:"syncBackToGrid,omitempty"`
	// Transition to island on grid loss enable
	TransToIslndOnGridLossEnabled *commonmodule.ControlDPC `protobuf:"bytes,10,opt,name=transToIslndOnGridLossEnabled,proto3" json:"transToIslndOnGridLossEnabled,omitempty"`
	// Enable voltage set point
	VoltageSetPointEnabled *commonmodule.ControlDPC `protobuf:"bytes,11,opt,name=voltageSetPointEnabled,proto3" json:"voltageSetPointEnabled,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *GenerationPointStatus) Reset()         { *m = GenerationPointStatus{} }
func (m *GenerationPointStatus) String() string { return proto.CompactTextString(m) }
func (*GenerationPointStatus) ProtoMessage()    {}
func (*GenerationPointStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{9}
}

func (m *GenerationPointStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationPointStatus.Unmarshal(m, b)
}
func (m *GenerationPointStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationPointStatus.Marshal(b, m, deterministic)
}
func (m *GenerationPointStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationPointStatus.Merge(m, src)
}
func (m *GenerationPointStatus) XXX_Size() int {
	return xxx_messageInfo_GenerationPointStatus.Size(m)
}
func (m *GenerationPointStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationPointStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationPointStatus proto.InternalMessageInfo

func (m *GenerationPointStatus) GetBlackStartEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.BlackStartEnabled
	}
	return nil
}

func (m *GenerationPointStatus) GetFrequencySetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.FrequencySetPointEnabled
	}
	return nil
}

func (m *GenerationPointStatus) GetPctHzDroop() *wrappers.FloatValue {
	if m != nil {
		return m.PctHzDroop
	}
	return nil
}

func (m *GenerationPointStatus) GetPctVDroop() *wrappers.FloatValue {
	if m != nil {
		return m.PctVDroop
	}
	return nil
}

func (m *GenerationPointStatus) GetRampRates() *commonmodule.RampRate {
	if m != nil {
		return m.RampRates
	}
	return nil
}

func (m *GenerationPointStatus) GetReactivePwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.ReactivePwrSetPointEnabled
	}
	return nil
}

func (m *GenerationPointStatus) GetRealPwrSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.RealPwrSetPointEnabled
	}
	return nil
}

func (m *GenerationPointStatus) GetState() *commonmodule.Optional_StateKind {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GenerationPointStatus) GetSyncBackToGrid() *commonmodule.ControlDPC {
	if m != nil {
		return m.SyncBackToGrid
	}
	return nil
}

func (m *GenerationPointStatus) GetTransToIslndOnGridLossEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.TransToIslndOnGridLossEnabled
	}
	return nil
}

func (m *GenerationPointStatus) GetVoltageSetPointEnabled() *commonmodule.ControlDPC {
	if m != nil {
		return m.VoltageSetPointEnabled
	}
	return nil
}

// Specialized 61850 ZGEN class
type GenerationEventAndStatusZGEN struct {
	// UML inherited base object
	LogicalNodeForEventAndStatus *commonmodule.LogicalNodeForEventAndStatus `protobuf:"bytes,1,opt,name=logicalNodeForEventAndStatus,proto3" json:"logicalNodeForEventAndStatus,omitempty"`
	// MISSING DOCUMENTATION!!!
	AuxPwrSt *commonmodule.StatusSPS `protobuf:"bytes,2,opt,name=AuxPwrSt,proto3" json:"AuxPwrSt,omitempty"`
	// MISSING DOCUMENTATION!!!
	DynamicTest *commonmodule.ENS_DynamicTestKind `protobuf:"bytes,3,opt,name=DynamicTest,proto3" json:"DynamicTest,omitempty"`
	// Emergency stop
	EmgStop *commonmodule.StatusSPS `protobuf:"bytes,4,opt,name=EmgStop,proto3" json:"EmgStop,omitempty"`
	// Generator is synchronized to EPS, or not; True = Synchronized
	GnSynSt *commonmodule.StatusSPS `protobuf:"bytes,5,opt,name=GnSynSt,proto3" json:"GnSynSt,omitempty"`
	// Point status
	PointStatus          *GenerationPointStatus `protobuf:"bytes,6,opt,name=PointStatus,proto3" json:"PointStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GenerationEventAndStatusZGEN) Reset()         { *m = GenerationEventAndStatusZGEN{} }
func (m *GenerationEventAndStatusZGEN) String() string { return proto.CompactTextString(m) }
func (*GenerationEventAndStatusZGEN) ProtoMessage()    {}
func (*GenerationEventAndStatusZGEN) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{10}
}

func (m *GenerationEventAndStatusZGEN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationEventAndStatusZGEN.Unmarshal(m, b)
}
func (m *GenerationEventAndStatusZGEN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationEventAndStatusZGEN.Marshal(b, m, deterministic)
}
func (m *GenerationEventAndStatusZGEN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationEventAndStatusZGEN.Merge(m, src)
}
func (m *GenerationEventAndStatusZGEN) XXX_Size() int {
	return xxx_messageInfo_GenerationEventAndStatusZGEN.Size(m)
}
func (m *GenerationEventAndStatusZGEN) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationEventAndStatusZGEN.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationEventAndStatusZGEN proto.InternalMessageInfo

func (m *GenerationEventAndStatusZGEN) GetLogicalNodeForEventAndStatus() *commonmodule.LogicalNodeForEventAndStatus {
	if m != nil {
		return m.LogicalNodeForEventAndStatus
	}
	return nil
}

func (m *GenerationEventAndStatusZGEN) GetAuxPwrSt() *commonmodule.StatusSPS {
	if m != nil {
		return m.AuxPwrSt
	}
	return nil
}

func (m *GenerationEventAndStatusZGEN) GetDynamicTest() *commonmodule.ENS_DynamicTestKind {
	if m != nil {
		return m.DynamicTest
	}
	return nil
}

func (m *GenerationEventAndStatusZGEN) GetEmgStop() *commonmodule.StatusSPS {
	if m != nil {
		return m.EmgStop
	}
	return nil
}

func (m *GenerationEventAndStatusZGEN) GetGnSynSt() *commonmodule.StatusSPS {
	if m != nil {
		return m.GnSynSt
	}
	return nil
}

func (m *GenerationEventAndStatusZGEN) GetPointStatus() *GenerationPointStatus {
	if m != nil {
		return m.PointStatus
	}
	return nil
}

// Specialized generation event ZGEN
type GenerationEventZGEN struct {
	// UML inherited base object
	GenerationEventAndStatusZGEN *GenerationEventAndStatusZGEN `protobuf:"bytes,1,opt,name=generationEventAndStatusZGEN,proto3" json:"generationEventAndStatusZGEN,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *GenerationEventZGEN) Reset()         { *m = GenerationEventZGEN{} }
func (m *GenerationEventZGEN) String() string { return proto.CompactTextString(m) }
func (*GenerationEventZGEN) ProtoMessage()    {}
func (*GenerationEventZGEN) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{11}
}

func (m *GenerationEventZGEN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationEventZGEN.Unmarshal(m, b)
}
func (m *GenerationEventZGEN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationEventZGEN.Marshal(b, m, deterministic)
}
func (m *GenerationEventZGEN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationEventZGEN.Merge(m, src)
}
func (m *GenerationEventZGEN) XXX_Size() int {
	return xxx_messageInfo_GenerationEventZGEN.Size(m)
}
func (m *GenerationEventZGEN) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationEventZGEN.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationEventZGEN proto.InternalMessageInfo

func (m *GenerationEventZGEN) GetGenerationEventAndStatusZGEN() *GenerationEventAndStatusZGEN {
	if m != nil {
		return m.GenerationEventAndStatusZGEN
	}
	return nil
}

// Generation event
type GenerationEvent struct {
	// UML inherited base object
	EventValue *commonmodule.EventValue `protobuf:"bytes,1,opt,name=eventValue,proto3" json:"eventValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationEventZGEN  *GenerationEventZGEN `protobuf:"bytes,2,opt,name=generationEventZGEN,proto3" json:"generationEventZGEN,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenerationEvent) Reset()         { *m = GenerationEvent{} }
func (m *GenerationEvent) String() string { return proto.CompactTextString(m) }
func (*GenerationEvent) ProtoMessage()    {}
func (*GenerationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{12}
}

func (m *GenerationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationEvent.Unmarshal(m, b)
}
func (m *GenerationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationEvent.Marshal(b, m, deterministic)
}
func (m *GenerationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationEvent.Merge(m, src)
}
func (m *GenerationEvent) XXX_Size() int {
	return xxx_messageInfo_GenerationEvent.Size(m)
}
func (m *GenerationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationEvent proto.InternalMessageInfo

func (m *GenerationEvent) GetEventValue() *commonmodule.EventValue {
	if m != nil {
		return m.EventValue
	}
	return nil
}

func (m *GenerationEvent) GetGenerationEventZGEN() *GenerationEventZGEN {
	if m != nil {
		return m.GenerationEventZGEN
	}
	return nil
}

// Generation event profile
type GenerationEventProfile struct {
	// UML inherited base object
	EventMessageInfo *commonmodule.EventMessageInfo `protobuf:"bytes,1,opt,name=eventMessageInfo,proto3" json:"eventMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	GeneratingUnit *GeneratingUnit `protobuf:"bytes,2,opt,name=generatingUnit,proto3" json:"generatingUnit,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationEvent *GenerationEvent `protobuf:"bytes,3,opt,name=generationEvent,proto3" json:"generationEvent,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerationEventProfile) Reset()         { *m = GenerationEventProfile{} }
func (m *GenerationEventProfile) String() string { return proto.CompactTextString(m) }
func (*GenerationEventProfile) ProtoMessage()    {}
func (*GenerationEventProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{13}
}

func (m *GenerationEventProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationEventProfile.Unmarshal(m, b)
}
func (m *GenerationEventProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationEventProfile.Marshal(b, m, deterministic)
}
func (m *GenerationEventProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationEventProfile.Merge(m, src)
}
func (m *GenerationEventProfile) XXX_Size() int {
	return xxx_messageInfo_GenerationEventProfile.Size(m)
}
func (m *GenerationEventProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationEventProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationEventProfile proto.InternalMessageInfo

func (m *GenerationEventProfile) GetEventMessageInfo() *commonmodule.EventMessageInfo {
	if m != nil {
		return m.EventMessageInfo
	}
	return nil
}

func (m *GenerationEventProfile) GetGeneratingUnit() *GeneratingUnit {
	if m != nil {
		return m.GeneratingUnit
	}
	return nil
}

func (m *GenerationEventProfile) GetGenerationEvent() *GenerationEvent {
	if m != nil {
		return m.GenerationEvent
	}
	return nil
}

func (m *GenerationEventProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

// Specialized 61850 ZGEN class
type GenerationStatusZGEN struct {
	// UML inherited base object
	GenerationEventAndStatusZGEN *GenerationEventAndStatusZGEN `protobuf:"bytes,1,opt,name=generationEventAndStatusZGEN,proto3" json:"generationEventAndStatusZGEN,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *GenerationStatusZGEN) Reset()         { *m = GenerationStatusZGEN{} }
func (m *GenerationStatusZGEN) String() string { return proto.CompactTextString(m) }
func (*GenerationStatusZGEN) ProtoMessage()    {}
func (*GenerationStatusZGEN) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{14}
}

func (m *GenerationStatusZGEN) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationStatusZGEN.Unmarshal(m, b)
}
func (m *GenerationStatusZGEN) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationStatusZGEN.Marshal(b, m, deterministic)
}
func (m *GenerationStatusZGEN) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationStatusZGEN.Merge(m, src)
}
func (m *GenerationStatusZGEN) XXX_Size() int {
	return xxx_messageInfo_GenerationStatusZGEN.Size(m)
}
func (m *GenerationStatusZGEN) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationStatusZGEN.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationStatusZGEN proto.InternalMessageInfo

func (m *GenerationStatusZGEN) GetGenerationEventAndStatusZGEN() *GenerationEventAndStatusZGEN {
	if m != nil {
		return m.GenerationEventAndStatusZGEN
	}
	return nil
}

// Generation status
type GenerationStatus struct {
	// UML inherited base object
	StatusValue *commonmodule.StatusValue `protobuf:"bytes,1,opt,name=statusValue,proto3" json:"statusValue,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationStatusZGEN *GenerationStatusZGEN `protobuf:"bytes,2,opt,name=generationStatusZGEN,proto3" json:"generationStatusZGEN,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GenerationStatus) Reset()         { *m = GenerationStatus{} }
func (m *GenerationStatus) String() string { return proto.CompactTextString(m) }
func (*GenerationStatus) ProtoMessage()    {}
func (*GenerationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{15}
}

func (m *GenerationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationStatus.Unmarshal(m, b)
}
func (m *GenerationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationStatus.Marshal(b, m, deterministic)
}
func (m *GenerationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationStatus.Merge(m, src)
}
func (m *GenerationStatus) XXX_Size() int {
	return xxx_messageInfo_GenerationStatus.Size(m)
}
func (m *GenerationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationStatus proto.InternalMessageInfo

func (m *GenerationStatus) GetStatusValue() *commonmodule.StatusValue {
	if m != nil {
		return m.StatusValue
	}
	return nil
}

func (m *GenerationStatus) GetGenerationStatusZGEN() *GenerationStatusZGEN {
	if m != nil {
		return m.GenerationStatusZGEN
	}
	return nil
}

// Generation status profile
type GenerationStatusProfile struct {
	// UML inherited base object
	StatusMessageInfo *commonmodule.StatusMessageInfo `protobuf:"bytes,1,opt,name=statusMessageInfo,proto3" json:"statusMessageInfo,omitempty"`
	// MISSING DOCUMENTATION!!!
	GeneratingUnit *GeneratingUnit `protobuf:"bytes,2,opt,name=generatingUnit,proto3" json:"generatingUnit,omitempty"`
	// MISSING DOCUMENTATION!!!
	GenerationStatus *GenerationStatus `protobuf:"bytes,3,opt,name=generationStatus,proto3" json:"generationStatus,omitempty"`
	// MISSING DOCUMENTATION!!!
	Ied                  *commonmodule.IED `protobuf:"bytes,4,opt,name=ied,proto3" json:"ied,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenerationStatusProfile) Reset()         { *m = GenerationStatusProfile{} }
func (m *GenerationStatusProfile) String() string { return proto.CompactTextString(m) }
func (*GenerationStatusProfile) ProtoMessage()    {}
func (*GenerationStatusProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4806d8aa84304e7d, []int{16}
}

func (m *GenerationStatusProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerationStatusProfile.Unmarshal(m, b)
}
func (m *GenerationStatusProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerationStatusProfile.Marshal(b, m, deterministic)
}
func (m *GenerationStatusProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerationStatusProfile.Merge(m, src)
}
func (m *GenerationStatusProfile) XXX_Size() int {
	return xxx_messageInfo_GenerationStatusProfile.Size(m)
}
func (m *GenerationStatusProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerationStatusProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GenerationStatusProfile proto.InternalMessageInfo

func (m *GenerationStatusProfile) GetStatusMessageInfo() *commonmodule.StatusMessageInfo {
	if m != nil {
		return m.StatusMessageInfo
	}
	return nil
}

func (m *GenerationStatusProfile) GetGeneratingUnit() *GeneratingUnit {
	if m != nil {
		return m.GeneratingUnit
	}
	return nil
}

func (m *GenerationStatusProfile) GetGenerationStatus() *GenerationStatus {
	if m != nil {
		return m.GenerationStatus
	}
	return nil
}

func (m *GenerationStatusProfile) GetIed() *commonmodule.IED {
	if m != nil {
		return m.Ied
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerationPoint)(nil), "generationmodule.GenerationPoint")
	proto.RegisterType((*GenerationCSG)(nil), "generationmodule.GenerationCSG")
	proto.RegisterType((*GenerationControlScheduleFSCH)(nil), "generationmodule.GenerationControlScheduleFSCH")
	proto.RegisterType((*GenerationControlFSCC)(nil), "generationmodule.GenerationControlFSCC")
	proto.RegisterType((*GenerationControl)(nil), "generationmodule.GenerationControl")
	proto.RegisterType((*GeneratingUnit)(nil), "generationmodule.GeneratingUnit")
	proto.RegisterType((*GenerationControlProfile)(nil), "generationmodule.GenerationControlProfile")
	proto.RegisterType((*GenerationReading)(nil), "generationmodule.GenerationReading")
	proto.RegisterType((*GenerationReadingProfile)(nil), "generationmodule.GenerationReadingProfile")
	proto.RegisterType((*GenerationPointStatus)(nil), "generationmodule.GenerationPointStatus")
	proto.RegisterType((*GenerationEventAndStatusZGEN)(nil), "generationmodule.GenerationEventAndStatusZGEN")
	proto.RegisterType((*GenerationEventZGEN)(nil), "generationmodule.GenerationEventZGEN")
	proto.RegisterType((*GenerationEvent)(nil), "generationmodule.GenerationEvent")
	proto.RegisterType((*GenerationEventProfile)(nil), "generationmodule.GenerationEventProfile")
	proto.RegisterType((*GenerationStatusZGEN)(nil), "generationmodule.GenerationStatusZGEN")
	proto.RegisterType((*GenerationStatus)(nil), "generationmodule.GenerationStatus")
	proto.RegisterType((*GenerationStatusProfile)(nil), "generationmodule.GenerationStatusProfile")
}

func init() {
	proto.RegisterFile("generationmodule/generationmodule.proto", fileDescriptor_4806d8aa84304e7d)
}

var fileDescriptor_4806d8aa84304e7d = []byte{
	// 1354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcb, 0x6f, 0xdc, 0x44,
	0x1c, 0x96, 0x93, 0xe6, 0xb1, 0xbf, 0xed, 0x23, 0x99, 0xbe, 0xdc, 0xd0, 0x47, 0x6a, 0x04, 0xad,
	0x90, 0xb2, 0x81, 0x16, 0x90, 0xa0, 0x12, 0x90, 0x6c, 0x36, 0xdb, 0x88, 0x26, 0x5d, 0xd9, 0x9b,
	0x28, 0x14, 0x89, 0x6a, 0xd6, 0x9e, 0xb8, 0x56, 0xed, 0x19, 0xd7, 0x9e, 0x4d, 0x1b, 0x4e, 0x9c,
	0x10, 0x17, 0x44, 0xff, 0x0e, 0x04, 0x37, 0x7a, 0xea, 0x01, 0xce, 0x48, 0x1c, 0x7a, 0xe3, 0xff,
	0xe0, 0xc0, 0x15, 0xd9, 0x1e, 0xaf, 0x67, 0x6d, 0xef, 0x3a, 0x0a, 0x44, 0x1c, 0xe0, 0x66, 0x7b,
	0xbe, 0xef, 0xfb, 0xbd, 0x67, 0x66, 0x17, 0x6e, 0xd8, 0x84, 0x92, 0x00, 0x73, 0x87, 0x51, 0x8f,
	0x59, 0x7d, 0x97, 0x2c, 0xe7, 0x3f, 0x34, 0xfc, 0x80, 0x71, 0x86, 0xe6, 0xf2, 0xdf, 0x17, 0x6a,
	0x7d, 0xcf, 0x4d, 0x16, 0x17, 0xae, 0xda, 0x8c, 0xd9, 0x2e, 0x59, 0x8e, 0xdf, 0x7a, 0xfd, 0xbd,
	0xe5, 0xa7, 0x01, 0xf6, 0x7d, 0x12, 0x84, 0x62, 0xfd, 0x9a, 0xc9, 0x3c, 0x6f, 0x60, 0x41, 0x7e,
	0x49, 0x00, 0xda, 0x8f, 0x33, 0x70, 0xa6, 0x3d, 0x30, 0xd0, 0x61, 0x0e, 0xe5, 0x68, 0x1d, 0xe6,
	0x7b, 0x2e, 0x36, 0x1f, 0x1b, 0x1c, 0x07, 0xbc, 0x45, 0x71, 0xcf, 0x25, 0x96, 0xaa, 0x2c, 0x2a,
	0x37, 0xeb, 0xb7, 0xd4, 0xc6, 0x90, 0x46, 0x93, 0x51, 0x1e, 0x30, 0x77, 0xad, 0xd3, 0xd4, 0x8b,
	0x14, 0xd4, 0x05, 0x75, 0x2f, 0x20, 0x4f, 0xfa, 0x84, 0x9a, 0x07, 0x06, 0xe1, 0xb1, 0x78, 0x2a,
	0x37, 0x51, 0x21, 0x37, 0x92, 0x89, 0xee, 0x00, 0xf8, 0x26, 0xbf, 0xfb, 0xe5, 0x5a, 0xc0, 0x98,
	0xaf, 0x4e, 0xc6, 0x3a, 0xaf, 0x35, 0x92, 0x3c, 0x34, 0xd2, 0x3c, 0x34, 0xd6, 0x5d, 0x86, 0xf9,
	0x0e, 0x76, 0xfb, 0x44, 0x97, 0xe0, 0xe8, 0x03, 0xa8, 0xf9, 0x26, 0xdf, 0x49, 0xb8, 0x27, 0xaa,
	0xb9, 0x19, 0x1a, 0xbd, 0x0b, 0xb5, 0x00, 0x7b, 0xbe, 0x8e, 0x39, 0x09, 0xd5, 0xa9, 0x98, 0x7a,
	0x61, 0xd8, 0x7d, 0x5d, 0x2c, 0xeb, 0x19, 0x10, 0xed, 0xc2, 0x42, 0x40, 0xb0, 0xc9, 0x9d, 0x7d,
	0xd2, 0x79, 0x1a, 0xe4, 0xb3, 0x30, 0x5d, 0x91, 0x85, 0x31, 0x5c, 0xd4, 0x81, 0x0b, 0x01, 0xc1,
	0x6e, 0x89, 0xea, 0x4c, 0x85, 0xea, 0x08, 0x1e, 0x6a, 0xc0, 0x54, 0x40, 0x42, 0xc2, 0xd5, 0xd9,
	0x0a, 0x81, 0x04, 0x86, 0xde, 0x87, 0xa9, 0x90, 0x63, 0x4e, 0xd4, 0x5a, 0x8c, 0x5f, 0x1c, 0xc6,
	0xdf, 0xf7, 0xa3, 0x8e, 0xc2, 0xee, 0x43, 0x23, 0xc2, 0x7c, 0xea, 0x50, 0x4b, 0x4f, 0xe0, 0xe8,
	0x13, 0x38, 0x1d, 0x1e, 0x50, 0x73, 0x15, 0x9b, 0x8f, 0xbb, 0xac, 0x1d, 0x38, 0x96, 0x0a, 0x15,
	0x06, 0x73, 0x78, 0xf4, 0x05, 0x5c, 0xe1, 0x01, 0xa6, 0x61, 0x97, 0x6d, 0x84, 0x2e, 0xb5, 0xee,
	0xd3, 0xe8, 0xeb, 0x3d, 0x16, 0x86, 0x69, 0x0a, 0xea, 0x15, 0x82, 0xe3, 0xe9, 0x51, 0x6e, 0xf7,
	0x99, 0xcb, 0xb1, 0x4d, 0xf2, 0xb9, 0x3d, 0x59, 0x95, 0xdb, 0x72, 0x1e, 0x5a, 0x87, 0x5a, 0x18,
	0xcd, 0x46, 0xd7, 0xf1, 0x88, 0x7a, 0x2a, 0x16, 0xb9, 0x5a, 0x2a, 0x12, 0x01, 0x42, 0x8e, 0x3d,
	0x7f, 0x75, 0xf6, 0x9b, 0x17, 0xaa, 0xf2, 0xfc, 0x85, 0xaa, 0xe8, 0x19, 0x55, 0xeb, 0xc2, 0xa9,
	0x6c, 0x5c, 0x9b, 0x46, 0x1b, 0x35, 0x61, 0xda, 0x0c, 0xf6, 0x3b, 0x3c, 0x54, 0x95, 0xc5, 0xc9,
	0x9b, 0xf5, 0x5b, 0xd7, 0x1b, 0x85, 0x7d, 0x24, 0x37, 0xdf, 0x92, 0xb0, 0xa0, 0x6a, 0x16, 0x5c,
	0x91, 0x54, 0x13, 0x47, 0x0c, 0xf3, 0x11, 0x89, 0xe8, 0xeb, 0x46, 0xf3, 0x2e, 0x6a, 0xc2, 0xcc,
	0x0e, 0x76, 0xd7, 0x9a, 0x46, 0x5b, 0x6c, 0x04, 0xd7, 0xc6, 0x99, 0x69, 0x1a, 0x6d, 0xc9, 0x48,
	0xca, 0xd4, 0x5e, 0x29, 0x70, 0xbe, 0x60, 0x66, 0xdd, 0x68, 0x36, 0xd1, 0x0a, 0xd4, 0xcd, 0xec,
	0x55, 0x98, 0xb8, 0x54, 0x9a, 0x9f, 0x08, 0xb0, 0x7a, 0xe2, 0xab, 0x48, 0x58, 0xe6, 0xa0, 0x7e,
	0x45, 0x08, 0x62, 0xc7, 0x59, 0x1e, 0xeb, 0x77, 0x91, 0xa6, 0x8f, 0x57, 0xd5, 0xfe, 0x54, 0x60,
	0xbe, 0x80, 0x40, 0x6b, 0x70, 0x52, 0xf8, 0x16, 0x6f, 0x23, 0x22, 0xa0, 0x85, 0xd2, 0x80, 0x62,
	0x84, 0x88, 0x68, 0x88, 0x85, 0x6e, 0xc3, 0x94, 0xf9, 0x88, 0x98, 0x8f, 0x85, 0xeb, 0x57, 0x72,
	0xf4, 0x68, 0xa9, 0xc9, 0xa8, 0xe5, 0x44, 0x96, 0x43, 0x3d, 0xc1, 0x22, 0x1b, 0xce, 0xdb, 0x65,
	0x39, 0x16, 0x3b, 0xe5, 0x8d, 0x43, 0xc4, 0x1f, 0xa7, 0x38, 0xab, 0x5f, 0xb9, 0x9e, 0xf6, 0x83,
	0x02, 0xa7, 0x53, 0x2a, 0xb5, 0xb7, 0xa9, 0xc3, 0xd1, 0x67, 0x70, 0xd6, 0x64, 0xd4, 0xea, 0x9b,
	0xd1, 0x97, 0xd6, 0x93, 0xbe, 0xe3, 0x7b, 0x84, 0x72, 0x11, 0xfd, 0xf5, 0x42, 0xf4, 0x79, 0xa0,
	0x48, 0x42, 0x99, 0x06, 0xfa, 0x18, 0x4e, 0x79, 0xf8, 0xd9, 0x7d, 0x5f, 0x98, 0xeb, 0x88, 0x9c,
	0xe4, 0x7a, 0x64, 0x25, 0xd9, 0x2c, 0xd9, 0x53, 0x12, 0xe8, 0xc3, 0x78, 0xed, 0xf7, 0x09, 0x50,
	0x0b, 0x91, 0x76, 0x02, 0xb6, 0xe7, 0xb8, 0x04, 0xed, 0x00, 0x12, 0x99, 0xdf, 0x24, 0x61, 0x88,
	0x6d, 0xb2, 0x41, 0xf7, 0x98, 0xf0, 0x7b, 0xb1, 0xb4, 0x6a, 0x12, 0x4e, 0xb8, 0x5d, 0xa2, 0x80,
	0x74, 0x38, 0x6d, 0x0f, 0xa5, 0x48, 0xb8, 0xbd, 0x38, 0xba, 0x0a, 0x09, 0x4e, 0x4a, 0x7f, 0x4e,
	0x01, 0x7d, 0x0e, 0xf3, 0x85, 0x82, 0x88, 0xe2, 0xbe, 0x7e, 0x88, 0xe2, 0x4a, 0xca, 0x45, 0x1d,
	0xb4, 0x04, 0x93, 0x0e, 0xb1, 0xc4, 0xc9, 0x38, 0x3f, 0x1c, 0xf9, 0x46, 0x6b, 0x4d, 0x22, 0x47,
	0xb8, 0x0f, 0x4f, 0xfc, 0xf2, 0x87, 0xaa, 0x68, 0xbf, 0x4d, 0xc8, 0x33, 0xa0, 0x13, 0x6c, 0x39,
	0xd4, 0x46, 0x5f, 0x2b, 0xa0, 0x95, 0x54, 0xb2, 0x4b, 0x02, 0xcf, 0xa1, 0xd8, 0x15, 0x30, 0x91,
	0xe4, 0xb7, 0x2b, 0x9b, 0x23, 0xc7, 0x13, 0x49, 0x3f, 0x84, 0x05, 0xf4, 0x1e, 0xd4, 0xfc, 0x47,
	0x38, 0x24, 0x9b, 0x9b, 0xdd, 0x2d, 0x91, 0xff, 0x8b, 0xc3, 0xe6, 0x3a, 0xe9, 0xb2, 0x9e, 0x21,
	0xd1, 0x1d, 0xa8, 0x07, 0x89, 0xc2, 0xe6, 0x66, 0x57, 0x17, 0x19, 0xce, 0xf5, 0x9b, 0x9e, 0x01,
	0x74, 0x19, 0x3d, 0x44, 0xde, 0xdd, 0x16, 0xf9, 0x1c, 0x45, 0xde, 0xdd, 0xd6, 0x65, 0x74, 0xae,
	0x55, 0x05, 0x4c, 0x6a, 0xd5, 0x14, 0x5b, 0xd5, 0xaa, 0x7a, 0x01, 0x97, 0xb6, 0x6a, 0x51, 0xe1,
	0xf8, 0x5b, 0x35, 0x2d, 0xf8, 0x21, 0x5a, 0x35, 0xad, 0x71, 0x69, 0xab, 0xa6, 0x65, 0x3d, 0x52,
	0xab, 0xbe, 0x9c, 0x96, 0x8f, 0xa0, 0xf8, 0x38, 0x8c, 0xae, 0x27, 0xfd, 0xf0, 0xff, 0x4b, 0xef,
	0x7f, 0xf4, 0xd2, 0x3b, 0xb8, 0xc4, 0xce, 0xfe, 0xdd, 0x4b, 0x6c, 0xed, 0x9f, 0xbe, 0xc4, 0xc2,
	0x71, 0x5d, 0x62, 0xeb, 0x47, 0xbb, 0xc4, 0x6a, 0x3f, 0x4f, 0xc2, 0xe5, 0x6c, 0x7a, 0x5a, 0xfb,
	0x84, 0xf2, 0x15, 0x6a, 0x25, 0x03, 0xf4, 0xa0, 0xdd, 0xda, 0x42, 0x1c, 0x2e, 0xbb, 0xcc, 0x76,
	0x4c, 0xec, 0x6e, 0x31, 0x8b, 0xac, 0xb3, 0x60, 0x18, 0x23, 0xe6, 0xe9, 0xad, 0x61, 0xc3, 0xf7,
	0xc6, 0x30, 0xc4, 0x86, 0x35, 0x56, 0x15, 0xdd, 0x86, 0xd9, 0x95, 0xfe, 0xb3, 0xa8, 0xb6, 0xbc,
	0x7c, 0x7f, 0x4f, 0x70, 0x46, 0xc7, 0xd0, 0x07, 0x40, 0xd4, 0x84, 0xfa, 0xda, 0x01, 0xc5, 0x9e,
	0x63, 0x76, 0x49, 0xc8, 0xc5, 0x48, 0xe5, 0xee, 0x28, 0xad, 0x2d, 0xe3, 0xa1, 0x04, 0x8a, 0xcb,
	0x2f, 0xb3, 0xd0, 0x3b, 0x30, 0xd3, 0xf2, 0x6c, 0x83, 0x0f, 0xe6, 0x6a, 0xa4, 0xe1, 0x14, 0x17,
	0x51, 0xda, 0xd4, 0x38, 0xa0, 0x06, 0x17, 0xf3, 0x34, 0x9a, 0x22, 0x70, 0x68, 0x03, 0xea, 0xd2,
	0x4e, 0x25, 0xe6, 0xe7, 0x46, 0xe5, 0x3d, 0x3f, 0x81, 0xeb, 0x32, 0x57, 0xfb, 0x4e, 0x81, 0xb3,
	0xb9, 0x0a, 0xc6, 0x85, 0x7b, 0x06, 0x97, 0xed, 0x31, 0x85, 0x15, 0x85, 0x6b, 0x8c, 0xb3, 0x59,
	0x64, 0xa5, 0xc5, 0x1b, 0xa7, 0xac, 0xfd, 0xa4, 0xc8, 0x7f, 0x40, 0xc4, 0x00, 0xf4, 0x11, 0x00,
	0x89, 0x1e, 0xe4, 0xcb, 0x73, 0xae, 0x5b, 0x5b, 0x83, 0x75, 0x61, 0x45, 0x62, 0x20, 0x0c, 0x67,
	0xed, 0x62, 0x90, 0xa2, 0x37, 0xde, 0xa8, 0x0c, 0x22, 0xf6, 0x3d, 0x3b, 0x3e, 0xca, 0xb4, 0xb4,
	0x5f, 0x27, 0xe0, 0x42, 0x8e, 0x96, 0x9e, 0xd0, 0x1d, 0x98, 0x8b, 0x7d, 0x29, 0x9e, 0xcf, 0x57,
	0x4b, 0x62, 0x28, 0x9e, 0xce, 0x05, 0xf6, 0xb1, 0x9c, 0xcd, 0xdb, 0x70, 0x26, 0x17, 0xd7, 0x60,
	0x06, 0xaa, 0xf2, 0x23, 0xa9, 0xe6, 0x35, 0x8e, 0x76, 0x2a, 0x3f, 0x57, 0xe0, 0x5c, 0x66, 0x43,
	0xda, 0x4f, 0xfe, 0xbd, 0xb6, 0x7c, 0xa9, 0xc0, 0x5c, 0xde, 0xa5, 0xe8, 0x67, 0x6a, 0x18, 0x3f,
	0xc9, 0x8d, 0x79, 0xa9, 0x6c, 0x7e, 0xe5, 0xce, 0x94, 0x39, 0xc8, 0x82, 0x73, 0x76, 0x49, 0xa4,
	0xa2, 0xa0, 0x6f, 0x8e, 0x8b, 0x44, 0x8a, 0x20, 0xcb, 0x62, 0xa9, 0x9a, 0xf6, 0x6a, 0x02, 0x2e,
	0xe6, 0x89, 0x69, 0x7b, 0x1a, 0x30, 0x9f, 0x38, 0x54, 0xec, 0xcf, 0x6b, 0x65, 0xa1, 0x14, 0x1b,
	0xb4, 0xc8, 0x3f, 0x96, 0x0e, 0xdd, 0x85, 0xb9, 0x7c, 0x70, 0xa2, 0x45, 0xb5, 0xea, 0x34, 0x49,
	0xba, 0x05, 0x95, 0x23, 0x35, 0xe9, 0xea, 0xb7, 0x0a, 0xa8, 0xcc, 0x27, 0x74, 0xcf, 0xeb, 0x15,
	0xcc, 0x77, 0x94, 0x07, 0x5d, 0xdb, 0xe1, 0x2e, 0xee, 0x45, 0x62, 0xcb, 0x02, 0xb6, 0xec, 0x87,
	0xd1, 0x73, 0x98, 0xfd, 0x3b, 0x6b, 0xb3, 0x25, 0xb1, 0xb6, 0xc4, 0xfc, 0x70, 0x69, 0xf0, 0x3d,
	0x25, 0xe4, 0x75, 0xbf, 0x9f, 0x18, 0x69, 0xb2, 0x37, 0x1d, 0xb3, 0x6f, 0xff, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x16, 0xa2, 0x8d, 0x73, 0x49, 0x16, 0x00, 0x00,
}
